'use client';

/* ============================================================================
   GeometricModelingLab — an interactive "bench" for MODELLING WITH GEOMETRY:
   choosing a solid to stand for a real object, paying for the choice, and then
   using the model to answer questions the object itself will not answer.

        a grain silo is NOT a cylinder — but a cylinder is close enough
        V = π·r²·h          the model's capacity
        mass = ρ · V        density turns capacity into tonnes
        mass / floor = ρ·h  what a square metre of floor is carrying
        S = 2πr² + 2πrh     the metal you must buy — the thing to minimise

   Built for MAIS (math AI system, www.mais.ac), K-12.  GRADES 11–12 —
   CCSS G-MG.A.1 (use geometric shapes and their measures to describe objects),
   G-MG.A.2 (apply density based on area and volume in modelling situations)
   and G-MG.A.3 (apply geometric methods to solve design problems — satisfy a
   physical constraint, minimise cost).

   ---------------------------------------------------------------------------
   HOW THIS LAB STAYS DISTINCT  (the library's hard rule)
   ---------------------------------------------------------------------------
   Every solid in this library already has an owner, and this bench borrows all
   of them rather than re-deriving any:
     • CylinderLab   — owns the cylinder itself: where V = πr²h and the lateral
                       area come from.  This bench CITES those formulas and
                       never re-derives them; its subject starts one step later.
     • RevolutionLab — owns how a solid is generated by spinning a region.
     • SphereLab / ConeLab / PyramidLab — own their own volume arguments.
     • OptimizationLab — owns the DERIVATIVE test for a best (the sign change
                       + → 0 → −).  This bench deliberately does NOT use
                       calculus: its design step searches the whole-number
                       designs exhaustively, so the "best" is a certificate you
                       can read off a finite table.  A student meets the same
                       idea twice, by two honest routes.

   What no sibling owns, and this bench does: the MODELLING ACT — the object is
   not the solid, the solid is a decision, and the decision has a measurable
   error you accept on purpose.  Then two uses of the model that the solid alone
   cannot motivate: density, and a design constraint.

   EXACT ARITHMETIC IN COEFFICIENTS OF π.  Every dimension is a whole number, so
   the capacity, the metal, and the mass are all held as EXACT INTEGER
   COEFFICIENTS of π (V = π·r²h is stored as r²h, never as 3.14159…).  The
   design search is an exhaustive integer factorisation, so the minimum is
   proved, not estimated, and the CALIBRATED stamp is an integer equality.

   The block between MODEL:START and MODEL:END is pure, React-free JavaScript;
   audit-geometricmodeling.mjs slices it out and evaluates it, so the audit
   tests the code that ships.
   ========================================================================== */

import { useCallback, useEffect, useRef, useState } from 'react';

/* ==== MODEL:START — pure math. No React, no pixels, no DOM. =============== */

const R_RANGE = { min: 1, max: 8 };   // metres
const H_RANGE = { min: 1, max: 24 };  // metres
const RHO_RANGE = { min: 1, max: 12 }; // tonnes per cubic metre-ish; a whole number on purpose

/* G-MG.1 — the model's measures. Held as exact integer coefficients of π:
   V = π·volCoef, S = π·surfCoef. Nothing here is ever a decimal. */
const volCoef = (r, h) => r * r * h;              // V   = π r² h
const surfCoef = (r, h) => 2 * r * r + 2 * r * h; // S   = 2πr² + 2πrh  (closed tank)
const baseCoef = (r) => r * r;                    // A   = π r²

/* the object the bench is modelling: a silo whose TRUE capacity was measured,
   in the same π-coefficient units. The model will not match it exactly — that
   is the lesson, not a bug. */
const OBJECT = { name: 'grain silo', trueVolCoef: 147, r: 3, h: 16 };

/* G-MG.1 — the error you accept by calling a silo a cylinder. Held as an exact
   fraction of the true capacity so it is never a rounded percentage. */
function modelError(r, h, trueCoef) {
  const model = volCoef(r, h);
  const diff = model - trueCoef;
  return { model, trueCoef, diff, absDiff: Math.abs(diff) };
}
/* the error as a percentage — the one rounded number, and it is labelled */
function errorPercent(r, h, trueCoef) {
  if (trueCoef === 0) return null;
  return (100 * (volCoef(r, h) - trueCoef)) / trueCoef;
}

/* G-MG.2 — density. mass = ρ · V, so in coefficients: massCoef = ρ · volCoef.
   Exact, because ρ and the coefficient are both whole numbers. */
const massCoef = (r, h, rho) => rho * volCoef(r, h);
/* the area version: what one square metre of FLOOR is carrying. The π cancels
   exactly — mass/floor = ρ·π·r²h / (π·r²) = ρ·h — so this readout is a whole
   number with no π in it at all. That cancellation is the step's whole point. */
const massPerFloor = (h, rho) => rho * h;

/* G-MG.3 — the design problem. A tank must hold EXACTLY a required capacity;
   find the whole-number design that buys the least metal. The search is
   exhaustive over the dials, so the winner is proved, not estimated. */
function designs(requiredVolCoef) {
  const out = [];
  for (let r = R_RANGE.min; r <= R_RANGE.max; r++) {
    const rr = r * r;
    if (requiredVolCoef % rr !== 0) continue;
    const h = requiredVolCoef / rr;
    if (h < H_RANGE.min || h > H_RANGE.max) continue;
    out.push({ r, h, surf: surfCoef(r, h) });
  }
  return out.sort((a, b) => a.surf - b.surf || a.r - b.r);
}
function bestDesign(requiredVolCoef) {
  const all = designs(requiredVolCoef);
  return all.length ? all[0] : null;
}
/* a required capacity is only worth posing if there are at least two legal
   designs AND one of them is a strict winner — otherwise "minimise" is empty */
function isPosable(requiredVolCoef) {
  const all = designs(requiredVolCoef);
  return all.length >= 2 && all[0].surf < all[1].surf;
}

/* ---- parameters ---------------------------------------------------------
   Three dials, unlocked as the lesson needs them: the two that define the
   model, then the density that turns capacity into tonnes. */
const DIALS = [
  { key: 'r', label: 'r — the model’s radius (m)', min: R_RANGE.min, max: R_RANGE.max, step: 1 },
  { key: 'h', label: 'h — the model’s height (m)', min: H_RANGE.min, max: H_RANGE.max, step: 1 },
  { key: 'rho', label: 'ρ — density of the contents (t per m³)', min: RHO_RANGE.min, max: RHO_RANGE.max, step: 1 },
];
const START = { r: 3, h: 16, rho: 1 };

/* ---- calibration --------------------------------------------------------
   "The designer's stamp." A required capacity is posted; set r and h so the
   tank holds EXACTLY that capacity using the LEAST metal. Two conditions, both
   exact integers — a design that holds the right amount but wastes metal does
   not stamp, which is the difference between a solution and a good one. */
function makeTarget(prev, rnd) {
  const rand = rnd || Math.random;
  const posable = [];
  for (let v = 8; v <= 400; v++) if (isPosable(v)) posable.push(v);
  let t = null, guard = 0;
  while (guard < 999) {
    guard += 1;
    const v = posable[Math.floor(rand() * posable.length)];
    if (v == null) continue;
    if (prev && prev.required === v) continue;
    t = { required: v, best: bestDesign(v), options: designs(v).length };
    break;
  }
  if (!t) { const v = posable[0]; t = { required: v, best: bestDesign(v), options: designs(v).length }; }
  return t;
}
function isCalibrated(r, h, target) {
  if (!target || !target.best) return false;
  return volCoef(r, h) === target.required && surfCoef(r, h) === target.best.surf;
}
/* the meter: full only when the capacity is exact AND the metal is minimal */
function matchPercent(r, h, target) {
  if (!target || !target.best) return 0;
  const v = volCoef(r, h);
  if (v !== target.required) {
    const off = Math.abs(v - target.required) / target.required;
    return Math.max(0, Math.min(60, 60 * (1 - off)));
  }
  const s = surfCoef(r, h), best = target.best.surf;
  const worst = Math.max(best + 1, designs(target.required).slice(-1)[0].surf);
  return 60 + 40 * (1 - (s - best) / (worst - best || 1));
}

/* ---- the lesson ---------------------------------------------------------- */
const STEPS = [
  {
    title: 'The shape inside the thing',
    focus: 'model',
    unlock: 2,
    body:
      'A grain silo is not a cylinder. It has a domed roof, a sloped floor, ribs, a hatch. But a ' +
      'cylinder is CLOSE ENOUGH — and unlike the silo, a cylinder has formulas. Choosing the solid is ' +
      'the modelling act: you trade some truth for a capacity you can actually compute.',
    q: 'Why model the silo as a cylinder rather than measure the real thing?',
    choices: [
      'A cylinder has formulas — you can compute capacity, metal and mass from two numbers',
      'Because a silo really is a perfect cylinder',
      'Because cylinders are easier to draw',
    ],
    answer: 0,
    feedback:
      'The model is a decision made for LEVERAGE: two measurements (r and h) now answer questions the ' +
      'real object would need emptying and weighing to answer. The price is that every answer is ' +
      'approximate — which is only a problem if you forget it.',
  },
  {
    title: 'What the model costs you',
    focus: 'error',
    unlock: 2,
    body:
      'The silo’s true capacity was measured: 147π cubic metres. Your cylinder says π·r²h. Move the ' +
      'dials and watch the gap. A model is not right or wrong — it is off by an amount you should be ' +
      'able to state out loud.',
    q: 'Your model reads 144π and the true capacity is 147π. What should you say?',
    choices: [
      '“About 2% under — fine for ordering grain, not for a legal certificate”',
      '“The model is wrong, throw it away”',
      '“The silo is wrong, it should be 144π”',
    ],
    answer: 0,
    feedback:
      'Naming the error and the use in the same breath is the whole skill. A 2% under-estimate is ' +
      'harmless when you are ordering a delivery and unacceptable when you are certifying capacity. ' +
      'The model does not decide that — the question does.',
  },
  {
    title: 'Density: how much stuff per unit',
    focus: 'density',
    unlock: 3,
    body:
      'Capacity is space; DENSITY turns it into stuff. Wheat runs about 0.8 tonnes per cubic metre; ' +
      'sand about 1.6. Multiply: mass = ρ · V. The model’s whole purpose arrives here — the silo will ' +
      'not tell you its own tonnage, but the cylinder will.',
    q: 'Two silos have the same capacity, one holding wheat and one holding sand. What differs?',
    choices: [
      'The mass — same volume, different density, so different tonnage',
      'The volume — sand takes more room',
      'Nothing, capacity settles it',
    ],
    answer: 0,
    feedback:
      'Volume is geometry; mass is geometry × density. That is exactly why G-MG.2 exists as a separate ' +
      'idea from volume: the same shape carries different loads, and the load is what the floor, the ' +
      'lorry, and the price all care about.',
  },
  {
    title: 'Density on the floor',
    focus: 'floor',
    unlock: 3,
    body:
      'Now the area version. How much mass is each square metre of FLOOR carrying? Divide the mass by ' +
      'the base area — and watch the π cancel: ρ·π·r²h ÷ π·r² = ρ·h. The answer does not depend on the ' +
      'radius at all. A wider silo is not a heavier floor; a TALLER one is.',
    q: 'You double the radius, keeping the height. What happens to the load per square metre of floor?',
    choices: [
      'Nothing — it is ρ·h, and the radius cancelled',
      'It doubles, because the silo is bigger',
      'It quadruples, because the base area quadrupled',
    ],
    answer: 0,
    feedback:
      'Both the mass and the floor area grew by the same factor r², so the ratio is untouched. A wider ' +
      'silo holds more grain AND stands on more floor. Height is the only dial that presses harder — ' +
      'which is why silos are engineered by height, not width.',
  },
  {
    title: 'The design problem',
    focus: 'design',
    unlock: 2,
    body:
      'Turn it around. The capacity is now a REQUIREMENT, and the metal is a COST: S = 2πr² + 2πrh. ' +
      'Many whole-number designs hold the required amount; they do not cost the same. The table below ' +
      'lists every legal design, so the cheapest is not a guess — it is the smallest row.',
    q: 'Two tanks hold exactly the same volume. What makes one of them the better design?',
    choices: [
      'It has less surface area, so it costs less metal to build',
      'It is taller, so it takes less floor',
      'They are equally good — the volume is what was required',
    ],
    answer: 0,
    feedback:
      'A constraint says which designs are ALLOWED; a cost says which allowed design is BEST. Squat ' +
      'and skinny both waste metal — the cheapest cylinder is close to as wide as it is tall, and you ' +
      'can see the table bottom out there.',
  },
  {
    title: 'The designer’s stamp',
    focus: 'calib',
    unlock: 2,
    body:
      'Last challenge. A required capacity is posted. Set r and h so the tank holds EXACTLY that ' +
      'capacity — and does it with the LEAST metal of any legal design. Holding the right amount is ' +
      'only half; the stamp wants the cheapest one. Press New target for another.',
    calib: true,
  },
];

/* ==== MODEL:END ========================================================== */

/* ============================================================================
   COMPONENT
   ========================================================================== */
export default function GeometricModelingLab() {
  const [vals, setVals] = useState(START);
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState({});
  const [target, setTarget] = useState(null);

  const stageRef = useRef(null);
  const canvasRef = useRef(null);
  const sceneRef = useRef({});

  const current = STEPS[step];
  const focus = current.focus;
  const { r, h, rho } = vals;

  const V = volCoef(r, h);
  const S = surfCoef(r, h);
  const err = modelError(r, h, OBJECT.trueVolCoef);
  const errPct = errorPercent(r, h, OBJECT.trueVolCoef);

  sceneRef.current = { r, h, rho, focus, target };

  const calibrated = current.calib && target ? isCalibrated(r, h, target) : false;
  const pct = current.calib && target ? matchPercent(r, h, target) : 0;

  /* ---- the renderer: the object, and the solid laid over it -------------- */
  const draw = useCallback(() => {
    const stage = stageRef.current, canvas = canvasRef.current;
    if (!stage || !canvas) return;
    const W = stage.clientWidth, H = stage.clientHeight;
    if (!W || !H) return;
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    canvas.width = Math.round(W * dpr); canvas.height = Math.round(H * dpr);
    const ctx = canvas.getContext('2d');
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, W, H);

    const S2 = sceneRef.current;
    const INK = '#1c2b3a', SOFT = '#5b6b7b', CARM = '#c81e4f', BLUE = '#3a6ea5', GOLD = '#b8860b';

    // a metre in pixels, chosen so the tallest legal tank still fits
    const groundY = H * 0.86;
    const u = Math.min((H * 0.72) / H_RANGE.max, (W * 0.34) / R_RANGE.max);
    const cxp = W * 0.5;

    // ground line
    ctx.strokeStyle = 'rgba(28,43,58,0.45)'; ctx.lineWidth = 2;
    ctx.beginPath(); ctx.moveTo(W * 0.06, groundY); ctx.lineTo(W * 0.94, groundY); ctx.stroke();

    // the REAL object behind the model: a silo silhouette, softly drawn
    const or_ = OBJECT.r * u, oh = OBJECT.h * u;
    ctx.fillStyle = 'rgba(91,107,123,0.16)';
    ctx.strokeStyle = 'rgba(91,107,123,0.5)'; ctx.lineWidth = 1.5;
    ctx.beginPath();
    ctx.moveTo(cxp - or_, groundY);
    ctx.lineTo(cxp - or_, groundY - oh);
    ctx.quadraticCurveTo(cxp, groundY - oh - or_ * 0.9, cxp + or_, groundY - oh);
    ctx.lineTo(cxp + or_, groundY);
    ctx.closePath(); ctx.fill(); ctx.stroke();
    ctx.fillStyle = SOFT; ctx.font = '11px system-ui, sans-serif';
    ctx.textAlign = 'center'; ctx.textBaseline = 'top';
    ctx.fillText(`the real silo (measured ${OBJECT.trueVolCoef}π m³)`, cxp, groundY + 26);

    // the MODEL: a cylinder, carmine
    const mr = S2.r * u, mh = S2.h * u;
    const ell = Math.max(5, mr * 0.32);
    const top = groundY - mh;
    ctx.fillStyle = 'rgba(200,30,79,0.10)';
    ctx.strokeStyle = CARM; ctx.lineWidth = 2.5;
    ctx.beginPath();
    ctx.moveTo(cxp - mr, groundY);
    ctx.lineTo(cxp - mr, top);
    ctx.ellipse(cxp, top, mr, ell, 0, Math.PI, 0, false);
    ctx.lineTo(cxp + mr, groundY);
    ctx.ellipse(cxp, groundY, mr, ell, 0, 0, Math.PI, false);
    ctx.closePath(); ctx.fill(); ctx.stroke();
    // the top rim, drawn whole so it reads as a lid
    ctx.beginPath(); ctx.ellipse(cxp, top, mr, ell, 0, 0, Math.PI * 2); ctx.stroke();

    /* dimension marks, drawn OUTSIDE the solid so neither label sits on the
       drawing or collides with the object's caption */
    const hx = cxp - mr - 22;               // the height bar, clear to the left
    ctx.strokeStyle = BLUE; ctx.lineWidth = 1.5;
    ctx.beginPath(); ctx.moveTo(hx, top); ctx.lineTo(hx, groundY); ctx.stroke();
    for (const yy of [top, groundY]) {      // end ticks
      ctx.beginPath(); ctx.moveTo(hx - 4, yy); ctx.lineTo(hx + 4, yy); ctx.stroke();
    }
    ctx.fillStyle = BLUE; ctx.font = '600 12px ui-monospace, Menlo, monospace';
    ctx.textAlign = 'right'; ctx.textBaseline = 'middle';
    ctx.fillText(`h = ${S2.h}`, hx - 7, (top + groundY) / 2);

    const ry = groundY + 11;                // the radius bar, on its own line
    ctx.beginPath(); ctx.moveTo(cxp, ry); ctx.lineTo(cxp + mr, ry); ctx.stroke();
    for (const xx of [cxp, cxp + mr]) {
      ctx.beginPath(); ctx.moveTo(xx, ry - 4); ctx.lineTo(xx, ry + 4); ctx.stroke();
    }
    ctx.textAlign = 'left'; ctx.textBaseline = 'middle';
    ctx.fillText(`r = ${S2.r}`, cxp + mr + 7, ry);

    const F = S2.focus;

    // the floor patch, for the density-on-the-floor step
    if (F === 'floor') {
      ctx.fillStyle = 'rgba(184,134,11,0.22)';
      ctx.strokeStyle = GOLD; ctx.lineWidth = 2;
      ctx.beginPath(); ctx.ellipse(cxp, groundY, mr, ell, 0, 0, Math.PI * 2); ctx.fill(); ctx.stroke();
      ctx.fillStyle = GOLD; ctx.font = '600 12px ui-monospace, Menlo, monospace';
      ctx.textAlign = 'center'; ctx.textBaseline = 'bottom';
      ctx.fillText(`${massPerFloor(S2.h, S2.rho)} t per m² of floor`, cxp, groundY - ell - 6);
    }

    // the design table, for the design + calibration steps
    if (F === 'design' || F === 'calib') {
      const req = F === 'calib' && S2.target ? S2.target.required : volCoef(S2.r, S2.h);
      const rows = designs(req).slice(0, 6);
      const bx = W * 0.06, by = H * 0.06, lh = 17;
      ctx.fillStyle = 'rgba(255,255,255,0.9)';
      ctx.strokeStyle = 'rgba(28,43,58,0.2)'; ctx.lineWidth = 1;
      const bw = 168, bh = lh * (rows.length + 2) + 10;
      ctx.beginPath(); ctx.rect(bx, by, bw, bh); ctx.fill(); ctx.stroke();
      ctx.font = '600 11px ui-monospace, Menlo, monospace';
      ctx.textAlign = 'left'; ctx.textBaseline = 'top';
      ctx.fillStyle = INK;
      ctx.fillText(`designs holding ${req}π m³`, bx + 9, by + 7);
      ctx.fillStyle = SOFT;
      ctx.fillText('  r    h    metal', bx + 9, by + 7 + lh);
      rows.forEach((d, i) => {
        const isBest = i === 0;
        const isMine = d.r === S2.r && d.h === S2.h;
        ctx.fillStyle = isBest ? GOLD : isMine ? CARM : SOFT;
        ctx.font = `${isBest || isMine ? 700 : 400} 11px ui-monospace, Menlo, monospace`;
        ctx.fillText(
          `${String(d.r).padStart(3)}  ${String(d.h).padStart(3)}   ${String(d.surf).padStart(4)}π` +
          (isBest ? '  ←least' : ''),
          bx + 9, by + 7 + lh * (i + 2)
        );
      });
      if (rows.length === 0) {
        ctx.fillStyle = CARM;
        ctx.fillText('  no whole-number design', bx + 9, by + 7 + lh * 2);
      }
    }
    void INK;
  }, []);

  useEffect(() => { draw(); }, [vals, step, target, focus, draw]);
  useEffect(() => {
    const st = stageRef.current;
    if (!st || typeof ResizeObserver === 'undefined') return;
    const ro = new ResizeObserver(() => draw());
    ro.observe(st);
    return () => ro.disconnect();
  }, [draw]);

  useEffect(() => {
    if (current.calib && !target) { setTarget(makeTarget(null)); setVals((v) => ({ ...v, r: 1, h: 1 })); }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [step]);

  useEffect(() => {
    if (focus === 'model' || focus === 'error') setVals((v) => ({ ...v, r: 3, h: 16 }));
    if (focus === 'density' || focus === 'floor') setVals((v) => ({ ...v, r: 3, h: 16, rho: 4 }));
    if (focus === 'design') setVals((v) => ({ ...v, r: 2, h: 24 }));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [step]);

  const setDial = (key, v) => setVals((p) => ({ ...p, [key]: parseInt(v, 10) }));
  const choose = (i) => { if (answers[step] == null) setAnswers((p) => ({ ...p, [step]: i })); };
  const goNext = () => setStep((s) => Math.min(STEPS.length - 1, s + 1));
  const goBack = () => setStep((s) => Math.max(0, s - 1));
  const answered = answers[step] != null;
  const canNext = step < STEPS.length - 1 && (!current.q || answered);

  const spoken = (() => {
    if (focus === 'calib' && target)
      return `Required ${target.required} pi cubic metres. Your design holds ${V} pi using ${S} pi of metal.`;
    if (focus === 'floor') return `Each square metre of floor carries ${massPerFloor(h, rho)} tonnes.`;
    return `A cylinder of radius ${r} and height ${h} holds ${V} pi cubic metres.`;
  })();

  return (
    <div className="gmlab">
      <header className="head">
        <h1>Modelling With Geometry</h1>
        <p className="lede">
          A grain silo is <em>not</em> a cylinder — but a cylinder has formulas, and the silo does not.
          Choosing the solid is a <strong>decision</strong> with a measurable error. Then the model earns
          its keep twice: it weighs the contents, and it tells you the cheapest tank that meets a spec.
        </p>
      </header>

      <div className="bench">
        <section className="panel stage-panel">
          <div className="stage" ref={stageRef}>
            <canvas ref={canvasRef} aria-label={`A cylinder modelling a silo. ${spoken}`} role="img" />
            <span className="sr-only" aria-live="polite">{spoken}</span>
          </div>
          <div className="readout" role="group" aria-label="Exact readouts">
            <div className="cell">
              <span className="k">capacity V</span>
              <span className="v">{V}π m³</span>
            </div>
            <div className="cell">
              <span className="k">metal S</span>
              <span className="v">{S}π m²</span>
            </div>
            <div className="cell">
              <span className="k">base area</span>
              <span className="v">{baseCoef(r)}π m²</span>
            </div>
            <div className="cell">
              <span className="k">vs measured</span>
              <span className={'v ' + (err.diff === 0 ? 'ok' : '')}>
                {err.diff === 0 ? 'exact' : `${err.diff > 0 ? '+' : '−'}${err.absDiff}π`}
              </span>
            </div>
            {focus === 'error' && (
              <div className="cell wide">
                <span className="k">model error</span>
                <span className="v">
                  {V}π vs {OBJECT.trueVolCoef}π · {errPct == null ? '—' : `${errPct > 0 ? '+' : ''}${errPct.toFixed(1)}%`}{' '}
                  <em className="soft">(the one rounded number on this bench)</em>
                </span>
              </div>
            )}
            {(focus === 'density' || focus === 'floor') && (
              <div className="cell wide">
                <span className="k">mass = ρ · V</span>
                <span className="v">
                  {rho} × {V}π = {massCoef(r, h, rho)}π tonnes · floor load ρ·h = {massPerFloor(h, rho)} t/m²
                </span>
              </div>
            )}
            {(focus === 'design' || focus === 'calib') && (
              <div className="cell wide">
                <span className="k">legal whole-number designs</span>
                <span className="v">
                  {designs(focus === 'calib' && target ? target.required : V).length} found ·
                  cheapest {(() => {
                    const b = bestDesign(focus === 'calib' && target ? target.required : V);
                    return b ? ` r=${b.r}, h=${b.h} at ${b.surf}π m²` : ' none';
                  })()}
                </span>
              </div>
            )}
          </div>
        </section>

        <aside className="panel tutor">
          <div className="progress" role="list" aria-label="Lesson progress">
            {STEPS.map((_, i) => (
              <span key={i} role="listitem"
                className={'pip' + (i === step ? ' cur' : '') + (i < step ? ' done' : '')}
                aria-current={i === step ? 'step' : undefined} />
            ))}
          </div>
          <p className="eyebrow small">Step {step + 1} of {STEPS.length}</p>
          <h2>{current.title}</h2>
          <p className="body">{current.body}</p>

          {DIALS.slice(0, current.unlock).map((d) => (
            <label className="dial" key={d.key}>
              <span className="drole">{d.label}</span>
              <input type="range" min={d.min} max={d.max} step={d.step}
                value={vals[d.key]} aria-label={d.label}
                onChange={(e) => setDial(d.key, e.target.value)} />
              <output className="dv">{vals[d.key]}</output>
            </label>
          ))}

          {current.q && (
            <div className="quiz">
              <p className="q">{current.q}</p>
              <div className="choices">
                {current.choices.map((ch, i) => {
                  const chosen = answers[step];
                  let cls = 'choice';
                  if (chosen != null) {
                    if (i === current.answer) cls += ' correct';
                    else if (i === chosen) cls += ' wrong';
                    else cls += ' dim';
                  }
                  return (
                    <button type="button" key={i} className={cls} onClick={() => choose(i)} disabled={chosen != null}>
                      <span className="mark" aria-hidden="true">
                        {chosen != null && i === current.answer ? '✓' : chosen != null && i === chosen ? '✕' : ''}
                      </span>{ch}
                    </button>
                  );
                })}
              </div>
              {answered && <p className="feedback">{current.feedback}</p>}
            </div>
          )}

          {current.calib && target && (
            <div className="calib">
              <p className="calib-goal">
                Hold exactly <span className="mono goal">{target.required}π m³</span> using the least
                metal. <span className="mono">{target.options}</span> legal designs exist.
              </p>
              <div className="meter" aria-hidden="true">
                <div className="meter-fill" style={{ width: pct.toFixed(0) + '%' }} />
              </div>
              <div className="meter-row">
                <span className="mono">
                  holds {V}π · metal {S}π
                </span>
                {calibrated
                  ? <span className="stamp">CALIBRATED</span>
                  : <span className="mono hint">
                      {V === target.required ? 'right size — now cheaper' : 'wrong capacity'}
                    </span>}
              </div>
              <button type="button" className="btn ghost"
                onClick={() => { setTarget(makeTarget(target)); setVals((v) => ({ ...v, r: 1, h: 1 })); }}>
                New target
              </button>
            </div>
          )}

          <div className="nav">
            <button type="button" className="btn ghost" onClick={goBack} disabled={step === 0}>← Back</button>
            {step < STEPS.length - 1 ? (
              <button type="button" className="btn" onClick={goNext} disabled={!canNext}>
                {current.q && !answered ? 'Answer to continue' : 'Next →'}
              </button>
            ) : (
              <button type="button" className="btn" onClick={() => {
                setStep(0); setAnswers({}); setTarget(null); setVals(START);
              }}>Restart lab</button>
            )}
          </div>
        </aside>
      </div>

      <footer className="foot">
        <span className="mono">V = πr²h · mass = ρV · floor load = ρh · S = 2πr² + 2πrh</span>
        &nbsp;·&nbsp; every quantity an exact whole-number coefficient of π, drawn live on a
        dependency-free canvas.
      </footer>

      <style jsx>{`
        .gmlab{
          --page:#eff1ee;--paper:#fbfbf8;--ink:#1c2b3a;--ink-soft:#5b6b7b;
          --curve:#c81e4f;--quad:#c7d8e4;--ok:#1f8a5b;--blue:#3a6ea5;--gold:#b8860b;
          --mono:ui-monospace,'SF Mono',Menlo,Consolas,monospace;
          --serif:'Iowan Old Style',Palatino,Georgia,serif;
          background:var(--page);color:var(--ink);
          font:16px/1.55 system-ui,-apple-system,'Segoe UI',sans-serif;
          padding:28px 18px 44px;border-radius:16px;max-width:1120px;margin:0 auto;
        }
        .mono{font-family:var(--mono);}
        .sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0;}
        .eyebrow{font-size:11px;letter-spacing:.24em;text-transform:uppercase;color:var(--ink-soft);margin:0 0 6px;}
        .eyebrow.small{margin:0 0 4px;}
        h1{font-family:var(--serif);font-weight:600;font-size:clamp(26px,4vw,34px);margin:0 0 6px;}
        .lede{color:var(--ink-soft);margin:0 0 22px;max-width:64ch;}
        .bench{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:22px;align-items:start;}
        @media (max-width:920px){.bench{grid-template-columns:1fr;}}
        .panel{background:#fff;border:1px solid rgba(28,43,58,.15);border-radius:12px;box-shadow:0 1px 2px rgba(28,43,58,.05);}
        .stage-panel{padding:14px;}
        .stage{position:relative;width:100%;aspect-ratio:16/12;border:1px solid var(--quad);border-radius:8px;overflow:hidden;
          background:radial-gradient(120% 120% at 30% 18%,#fdfefe 0%,#eef3f7 60%,#e3ebf1 100%);}
        .stage canvas{display:block;width:100%;height:100%;}
        .readout{margin:12px 2px 2px;display:grid;grid-template-columns:repeat(4,1fr);gap:8px;}
        .cell{background:var(--paper);border:1px solid rgba(28,43,58,.14);border-radius:8px;padding:8px 10px;display:grid;gap:2px;}
        .cell.wide{grid-column:1/-1;}
        .cell .k{font-size:11px;letter-spacing:.06em;color:var(--ink-soft);font-family:var(--mono);}
        .cell .v{font-family:var(--mono);font-weight:700;font-size:15px;}
        .cell .v.ok{color:var(--ok);}
        .cell .soft{color:var(--ink-soft);font-weight:400;font-size:12px;font-style:normal;}
        @media (max-width:700px){.readout{grid-template-columns:repeat(2,1fr);}}
        .btn{font:600 14px/1 system-ui,sans-serif;padding:10px 16px;border-radius:8px;cursor:pointer;
          border:1px solid var(--ink);background:var(--ink);color:#fff;transition:filter .15s,opacity .15s;}
        .btn.ghost{background:transparent;color:var(--ink);}
        .btn:disabled{opacity:.4;cursor:not-allowed;}
        .btn:not(:disabled):hover{filter:brightness(1.08);}
        .tutor{padding:18px 20px 20px;}
        .progress{display:flex;gap:6px;margin-bottom:14px;}
        .pip{height:6px;flex:1;border-radius:3px;background:rgba(28,43,58,.14);}
        .pip.done{background:rgba(200,30,79,.45);}
        .pip.cur{background:var(--curve);}
        h2{font-family:var(--serif);font-weight:600;font-size:21px;margin:0 0 10px;padding-bottom:9px;border-bottom:3px double rgba(200,30,79,.45);}
        .body{margin:0 0 16px;font-size:14.5px;}
        .dial{display:grid;grid-template-columns:1fr 52px;grid-template-rows:auto auto;align-items:center;gap:2px 10px;margin-bottom:12px;}
        .drole{grid-column:1/3;font-size:12px;color:var(--ink-soft);}
        .dial input[type=range]{grid-column:1;width:100%;accent-color:var(--ink);cursor:pointer;}
        .dv{grid-column:2;font-family:var(--mono);text-align:right;font-size:17px;font-weight:700;}
        .quiz{margin-top:4px;}
        .q{font-size:14px;font-weight:600;margin:0 0 10px;}
        .choices{display:grid;gap:8px;}
        .choice{text-align:left;font:14px/1.4 system-ui,sans-serif;padding:11px 11px 11px 32px;
          border:1px solid rgba(28,43,58,.2);border-radius:8px;background:var(--paper);color:var(--ink);
          cursor:pointer;position:relative;transition:border-color .15s,background .15s;}
        .choice:not(:disabled):hover{border-color:var(--ink);}
        .choice .mark{position:absolute;left:11px;font-weight:700;}
        .choice.correct{border-color:var(--ok);background:rgba(31,138,91,.08);}
        .choice.correct .mark{color:var(--ok);}
        .choice.wrong{border-color:var(--ink-soft);background:rgba(91,107,123,.08);}
        .choice.wrong .mark{color:var(--ink-soft);}
        .choice.dim{opacity:.55;}
        .choice:disabled{cursor:default;}
        .feedback{margin:12px 0 0;font-size:13px;line-height:1.55;background:rgba(200,30,79,.05);
          border-left:3px solid var(--curve);padding:10px 12px;border-radius:0 6px 6px 0;}
        .calib{margin-top:6px;display:grid;gap:11px;}
        .calib-goal{margin:0;font-size:15px;background:rgba(58,110,165,.08);border-radius:8px;padding:11px 13px;}
        .calib-goal .mono{font-weight:700;}
        .calib-goal .goal{color:var(--curve);}
        .meter{height:12px;border-radius:6px;background:rgba(28,43,58,.1);overflow:hidden;}
        .meter-fill{height:100%;background:linear-gradient(90deg,rgba(200,30,79,.55),var(--curve));transition:width .12s ease-out;}
        .meter-row{display:flex;justify-content:space-between;align-items:center;gap:8px;font-size:13px;}
        .hint{color:var(--ink-soft);font-size:12.5px;}
        .stamp{font:700 12px/1 var(--mono);letter-spacing:.16em;color:var(--ok);border:2px solid var(--ok);border-radius:6px;padding:5px 9px;transform:rotate(-3deg);}
        .nav{margin-top:20px;display:flex;justify-content:space-between;gap:10px;}
        .foot{margin-top:24px;font-size:12.5px;color:var(--ink-soft);}
        :global(.gmlab) :focus-visible{outline:2px solid var(--ink);outline-offset:2px;border-radius:4px;}
        @media (prefers-reduced-motion:reduce){.btn,.choice,.meter-fill{transition:none;}}
      `}</style>
    </div>
  );
}
