'use client';

/* ============================================================================
   RevolutionLab — an interactive "bench" for SOLIDS OF REVOLUTION: the lathe.
   Spin a flat region about an axis and a solid appears — the rectangle turns
   into the cylinder, the right triangle into the cone, the half-disc into
   the sphere.  The three solid benches each measure their own solid; none of
   them shows WHERE the solids come from.  This bench is the common origin
   story, and every volume it posts is an exact integer (or exact fraction)
   times π.  (GRADES 9–12 · CCSS G-GMD.B.4 — identify three-dimensional
   objects generated by rotations of two-dimensional objects.)

   THE SIGNATURE CENTERPIECE — "THE LATHE AND THE VOLUME MANIFEST."  A gold
   axis runs vertically; the blue flat region hangs on its right; its faint
   mirror ghost on the left shows the sweep; and the carmine solid outline
   wraps both.  Beside the picture, the manifest prints the exact bill:
   spin the 3-by-4 rectangle and V = π·3²·4 = 36π; spin the 3-by-6 triangle
   and V = ⅓·π·3²·6 = 18π; spin the half-disc of radius 3 and V = 36π —
   and Archimedes' tombstone ratio, sphere to snug cylinder, lands on
   exactly 2/3.

   THE MODEL — exact integer/rational arithmetic throughout:
     · regions are {kind, dims}; solidOf reads the kind (rectangle →
       cylinder, right triangle → cone, half-disc → sphere) — one law each.
     · coefOf returns the volume's coefficient of π as a reduced exact
       fraction: [w²h, 1], [w²h, 3], [4r³, 3].  π itself is never
       evaluated; it rides as a symbol, and the audit proves every posted
       coefficient is an integer (dimensions are engineered so /3 divides).
     · the audit re-proves the cone = ⅓ of its bounding cylinder and the
       sphere = ⅔ of its snug cylinder as exact fraction identities, for
       every legal dimension in range — not just the posted ones.

   WHAT THIS LAB REFUSES TO DO (distinctness):
     · No formula derivations — the cylinder, cone, and sphere benches own
       measuring their own solids; each is cited as the destination bench,
       and the formulas arrive here as inherited freight.
     · No plane cuts, no flat shapes read off a solid — the cube-cutting
       bench owns that direction of G-GMD.B.4; this bench only ever goes
       flat-to-solid, never solid-to-flat.
     · No spinning animation — the sweep is drawn as a still ghost;
       requestAnimationFrame is banned by the audit.  Motion is implied,
       never performed.
     · No degree-slot machinery, no deposits — the polynomial bench owns
       its bookkeeping; this manifest tallies only coefficients of π.
   COLORS: one accent. CARMINE = the born solid (the object). GOLD = the
   axis and the manifest (the tool). BLUE = the quiet flat region. GREEN
   only on correct answers and the CALIBRATED stamp.

   THE CALIBRATION — a flat region is posted on the lathe.  Rule the solid
   it births first, then rule the volume's coefficient of π, exactly.
   Truths are derived from solidOf/coefOf at answer time; the meter is
   quantized to {0, 50, 100}; the coefficient earns nothing until the
   solid stands.  The stamp provably cannot fire falsely.
   ========================================================================== */

import { useCallback, useEffect, useRef, useState } from 'react';

/* ============================================================================
   MODEL — exact integer arithmetic; π rides as a symbol, never a float.
   ========================================================================== */
const CARMINE = '#c81e4f';
const BLUE = '#3f74a6';
const GOLD = '#b98718';
const INK_HEX = '#243342';
const SLATE = '#5b6b7b';
const CALIB_STEP = 5;
const MINUS = '−'; /* U+2212 */

const fmtInt = (n) => (n < 0 ? MINUS + String(-n) : String(n));
const gcdOf = (x, y) => {
  x = Math.abs(x);
  y = Math.abs(y);
  while (y) {
    const t = x % y;
    x = y;
    y = t;
  }
  return x || 1;
};

/* a flat region on the lathe */
const regionText = (rg) =>
  rg.kind === 'rect'
    ? `the ${rg.w}-by-${rg.h} rectangle`
    : rg.kind === 'tri'
      ? `the right triangle, base ${rg.w}, height ${rg.h}`
      : `the half-disc of radius ${rg.r}`;

/* one law each: what the spin births */
const solidOf = (rg) => (rg.kind === 'rect' ? 'cylinder' : rg.kind === 'tri' ? 'cone' : 'sphere');

/* the volume's coefficient of π, as a reduced exact fraction */
const coefOf = (rg) => {
  let n;
  let d;
  if (rg.kind === 'rect') {
    n = rg.w * rg.w * rg.h;
    d = 1;
  } else if (rg.kind === 'tri') {
    n = rg.w * rg.w * rg.h;
    d = 3;
  } else {
    n = 4 * rg.r * rg.r * rg.r;
    d = 3;
  }
  const g = gcdOf(n, d);
  return [n / g, d / g];
};
const coefText = ([n, d]) => (d === 1 ? String(n) : `${n}/${d}`);
const volumeText = (rg) => `${coefText(coefOf(rg))}π`;

/* the lesson's posted regions */
const SCENES = {
  cyl: { kind: 'rect', w: 3, h: 4 },
  cone: { kind: 'tri', w: 3, h: 6 },
  sph: { kind: 'half', r: 3 },
  dial: { kind: 'rect', w: 3, h: 4 },
};

/* ---------------------------------------------------------------------------
   CALIBRATION — posted regions; truths derived from the lathe's laws.
   ------------------------------------------------------------------------- */
const CASES = [
  { kind: 'rect', w: 3, h: 4 },
  { kind: 'half', r: 3 },
  { kind: 'tri', w: 3, h: 6 },
  { kind: 'rect', w: 2, h: 5 },
  { kind: 'tri', w: 2, h: 6 },
  { kind: 'tri', w: 3, h: 3 },
];
const SOLID_CHIPS = ['cylinder', 'cone', 'sphere'];
const COEF_CHIPS = ['8', '9', '18', '20', '36'];

const labelOf = (i) => regionText(CASES[i]);
const solidTruth = (i) => solidOf(CASES[i]);
const coefTruth = (i) => coefText(coefOf(CASES[i]));

const makeCase = (prev) => {
  let k = Math.floor(Math.random() * CASES.length);
  while (CASES.length > 1 && k === prev) k = Math.floor(Math.random() * CASES.length);
  return k;
};

const calibChecks = (i, sPick, cPick) => {
  if (i == null) return [false, false];
  const c1 = sPick === solidTruth(i);
  const c2 = c1 && cPick === coefTruth(i);
  return [c1, c2];
};
const closeness = (i, sPick, cPick) => {
  const [c1, c2] = calibChecks(i, sPick, cPick);
  return (c1 ? 50 : 0) + (c2 ? 50 : 0);
};
const isCalibrated = (i, sPick, cPick) => calibChecks(i, sPick, cPick).every(Boolean);

/* ---------------------------------------------------------------------------
   THE LESSON — six steps; every scene is pinned to the words describing it.
   ------------------------------------------------------------------------- */
const STEPS = [
  {
    title: 'The lathe’s one move',
    body:
      'Hang the 3-by-4 rectangle on the axis and spin. Every point sweeps a ' +
      'circle; the whole region sweeps a solid: a cylinder of radius 3 and ' +
      'height 4.',
    scene: 'cyl',
    q: 'Why is the cylinder’s radius the rectangle’s WIDTH?',
    choices: [
      'The rim of the solid is swept by the region’s farthest edge — width from the axis becomes reach, and reach becomes radius',
      'Because radius always equals the smaller dimension',
      'It isn’t — the radius is the height',
    ],
    answer: 0,
    feedback:
      'Distance from the axis is everything on a lathe: the edge 3 away sweeps ' +
      'the rim, so the radius is 3, and the height rides along unchanged. The ' +
      'cylinder bench measures this solid — π·3²·4 = 36π — and today that ' +
      'formula stops being a recipe and becomes a consequence of the spin.',
    note:
      'Watch what the manifest refuses to do: it never turns 36π into a ' +
      'decimal. The coefficient is the exact content; π is a symbol riding ' +
      'along — and every volume this bench will post keeps that form.',
  },
  {
    title: 'The triangle pays a third',
    body:
      'Swap in the right triangle — base 3 on the floor, height 6 up the axis ' +
      '— and spin. A cone appears: radius 3, height 6.',
    scene: 'cone',
    q: 'The bounding cylinder (radius 3, height 6) holds 54π. The cone holds…',
    choices: [
      '18π — exactly one third of the cylinder; the taper forfeits two thirds',
      '27π — exactly half',
      '54π — spinning fills the whole cylinder either way',
    ],
    answer: 0,
    feedback:
      'The cone bench posts V = ⅓·π·r²·h, so ⅓·π·9·6 = 18π against the ' +
      'cylinder’s 54π: the ratio is exactly 3, not roughly 3. The taper narrows ' +
      'the sweep as you climb, and the third is the exact price — an identity ' +
      'this bench’s audit re-proves for every legal base and height.',
    note:
      'Note which flat region did this: a triangle with its VERTICAL leg on ' +
      'the axis. Hang the same triangle by its horizontal leg instead and the ' +
      'lathe births a different cone — the region’s pose matters as much as ' +
      'its shape.',
  },
  {
    title: 'The half-disc closes the set',
    body:
      'Third region: the half-disc of radius 3, flat side on the axis. Spin — ' +
      'and the sphere appears.',
    scene: 'sph',
    q: 'Why the HALF-disc rather than the full disc?',
    choices: [
      'One half-turn of sweep already reaches everywhere — a full disc would cover every point of the sphere twice',
      'A full disc would spin into a cube',
      'Because spheres are half as big as discs',
    ],
    answer: 0,
    feedback:
      'The flat side hugs the axis and the curved rim sweeps the whole skin in ' +
      'one revolution: the sphere bench’s V = 4/3·π·r³ gives 4/3·π·27 = 36π, an ' +
      'exact integer coefficient because the radius is a multiple of 3. Three ' +
      'benches — cylinder, cone, sphere — now share a single origin: one axis, ' +
      'one spin, three regions. What looked like three formulas to memorize was ' +
      'one machine wearing three blades.',
    note:
      'The set is closed with remarkable economy: rectangle, triangle, ' +
      'half-disc — the three simplest flat shapes a lathe can hold produce the ' +
      'three solids an entire unit of geometry is built on.',
  },
  {
    title: 'Archimedes’ tombstone',
    body:
      'Put the sphere (36π) inside its snug cylinder — radius 3, height 6, ' +
      'volume 54π. Compare.',
    scene: 'sph',
    q: 'Sphere to snug cylinder, as an exact ratio?',
    choices: [
      '2/3 exactly — 36π against 54π; Archimedes had this very ratio carved on his tombstone',
      'About 0.67, never exact',
      '3/4 — spheres are three quarters of anything',
    ],
    answer: 0,
    feedback:
      '36/54 reduces to 2/3 — no rounding, no residue. Archimedes considered ' +
      'the sphere-in-cylinder ratio his finest theorem and asked for the figure ' +
      'on his grave. On this bench it is two manifest lines and one reduced ' +
      'fraction — which is exactly why the manifest never leaves exact form.',
    note:
      'The audit checks this identity at EVERY radius, not just 3: the sphere ' +
      'coefficient 4r³/3 against the snug cylinder’s 2r³ reduces to 2/3 ' +
      'symbolically. Tombstone theorems deserve better than spot checks.',
  },
  {
    title: 'Reach counts twice',
    body:
      'Put the rectangle’s width on the dial, height fixed at 4. Widths 1 ' +
      'through 5 give volumes 4π, 16π, 36π, 64π, 100π.',
    scene: 'dial',
    dial: true,
    q: 'Doubling the width quadruples the volume. Why?',
    choices: [
      'The rim sweeps a disc of area π·w² — distance from the axis enters squared, so reach counts twice',
      'It doesn’t — volume grows linearly with width',
      'Because 4 is the height',
    ],
    answer: 0,
    feedback:
      'Every layer of the cylinder is a swept disc of area π·w², and w² is ' +
      'where the quadrupling lives: 4π, 16π, 36π, 64π, 100π — the coefficients ' +
      'are 4w², perfect squares scaled by the height. On a lathe, distance ' +
      'from the axis is the loudest dimension there is.',
    note:
      'This is the deep reason lathes and doubled reach matter beyond ' +
      'geometry: capacity, momentum, and stiffness all inherit a w² from ' +
      'sweeping — one picture, many bills, and always the same square sitting ' +
      'in the middle of them.',
  },
  {
    title: 'The turner’s stamp',
    body:
      'A flat region is posted on the lathe. Rule the solid it births first — ' +
      'cylinder, cone, or sphere — then rule the volume’s coefficient of π, ' +
      'exactly. Both exact, or no stamp.',
    scene: 'cyl',
    calib: true,
  },
];

/* ============================================================================
   COMPONENT
   ========================================================================== */
export default function RevolutionLab() {
  const [wDial, setWDial] = useState(3);
  const [sPick, setSPick] = useState(null);
  const [cPick, setCPick] = useState(null);
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState({});
  const [kase, setKase] = useState(null);

  const stageRef = useRef(null);
  const canvasRef = useRef(null);
  const sceneRef = useRef({});

  const current = STEPS[step];
  const calib = !!current.calib;
  const region = calib && kase != null ? CASES[kase] : current.dial ? { kind: 'rect', w: wDial, h: 4 } : SCENES[current.scene];
  const solid = solidOf(region);
  const coef = coefOf(region);

  const checks = calib ? calibChecks(kase, sPick, cPick) : [false, false];
  const pct = calib && kase != null ? closeness(kase, sPick, cPick) : 0;
  const calibrated = calib && kase != null ? isCalibrated(kase, sPick, cPick) : false;

  const bandLabel = calib ? `posted: ${kase != null ? labelOf(kase) : ''}` : `${regionText(region)}, on the lathe`;
  sceneRef.current = { region, solid, coef, calib, bandLabel };

  /* ---- full redraw from state ------------------------------------------- */
  const draw = useCallback(() => {
    const stage = stageRef.current;
    const canvas = canvasRef.current;
    if (!stage || !canvas) return;
    const W = stage.clientWidth;
    const H2 = stage.clientHeight;
    if (W === 0 || H2 === 0) return;

    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    canvas.width = Math.round(W * dpr);
    canvas.height = Math.round(H2 * dpr);
    const ctx = canvas.getContext('2d');
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

    const S = sceneRef.current;
    ctx.clearRect(0, 0, W, H2);

    /* quadrille paper */
    ctx.lineWidth = 1;
    ctx.strokeStyle = 'rgba(199,216,228,0.5)';
    const gs = 26;
    ctx.beginPath();
    for (let gx = gs; gx < W; gx += gs) {
      ctx.moveTo(Math.round(gx) + 0.5, 0);
      ctx.lineTo(Math.round(gx) + 0.5, H2);
    }
    for (let gy = gs; gy < H2; gy += gs) {
      ctx.moveTo(0, Math.round(gy) + 0.5);
      ctx.lineTo(W, Math.round(gy) + 0.5);
    }
    ctx.stroke();

    const bandH = 52;
    const rg = S.region;
    const rMax = rg.kind === 'half' ? rg.r : rg.w;
    const hMax = rg.kind === 'half' ? 2 * rg.r : rg.h;
    const u = Math.min((W * 0.36) / Math.max(rMax, 1), (H2 - bandH - 150) / Math.max(hMax, 1));
    const ax = W * 0.46;
    const yBot = H2 - 80;
    const yTop = yBot - hMax * u;

    /* the axis */
    ctx.strokeStyle = GOLD;
    ctx.lineWidth = 2.4;
    ctx.setLineDash([7, 5]);
    ctx.beginPath();
    ctx.moveTo(ax, yTop - 26);
    ctx.lineTo(ax, yBot + 26);
    ctx.stroke();
    ctx.setLineDash([]);

    /* the region (right) and its sweep ghost (left) */
    const drawRegion = (side, alpha) => {
      ctx.fillStyle = `rgba(63,116,166,${alpha})`;
      ctx.beginPath();
      if (rg.kind === 'rect') {
        ctx.rect(side < 0 ? ax - rg.w * u : ax, yBot - rg.h * u, rg.w * u, rg.h * u);
      } else if (rg.kind === 'tri') {
        ctx.moveTo(ax, yBot);
        ctx.lineTo(ax + side * rg.w * u, yBot);
        ctx.lineTo(ax, yBot - rg.h * u);
        ctx.closePath();
      } else {
        ctx.arc(ax, yBot - rg.r * u, rg.r * u, side < 0 ? Math.PI / 2 : -Math.PI / 2, side < 0 ? (3 * Math.PI) / 2 : Math.PI / 2);
        ctx.closePath();
      }
      ctx.fill();
    };
    drawRegion(1, 0.5);
    drawRegion(-1, 0.14);

    /* the born solid's outline */
    ctx.strokeStyle = CARMINE;
    ctx.lineWidth = 2.4;
    const rr = rMax * u;
    if (S.solid === 'cylinder') {
      ctx.strokeRect(ax - rr, yTop, 2 * rr, hMax * u);
      for (const yy of [yTop, yBot]) {
        ctx.beginPath();
        ctx.ellipse(ax, yy, rr, rr * 0.22, 0, 0, 2 * Math.PI);
        ctx.stroke();
      }
    } else if (S.solid === 'cone') {
      ctx.beginPath();
      ctx.moveTo(ax - rr, yBot);
      ctx.lineTo(ax, yTop);
      ctx.lineTo(ax + rr, yBot);
      ctx.stroke();
      ctx.beginPath();
      ctx.ellipse(ax, yBot, rr, rr * 0.22, 0, 0, 2 * Math.PI);
      ctx.stroke();
    } else {
      ctx.beginPath();
      ctx.arc(ax, yBot - rg.r * u, rr, 0, 2 * Math.PI);
      ctx.stroke();
      ctx.beginPath();
      ctx.ellipse(ax, yBot - rg.r * u, rr, rr * 0.22, 0, 0, 2 * Math.PI);
      ctx.stroke();
    }

    /* the manifest */
    ctx.textAlign = 'left';
    ctx.textBaseline = 'top';
    ctx.fillStyle = SLATE;
    ctx.font = 'italic 600 11.5px system-ui, sans-serif';
    ctx.fillText('the volume manifest', 22, bandH + 8);
    ctx.font = '600 11.5px ui-monospace, monospace';
    ctx.fillStyle = CARMINE;
    ctx.fillText(S.calib ? 'births: ?' : `births: the ${S.solid}`, 22, bandH + 26);
    ctx.fillStyle = GOLD;
    ctx.fillText(S.calib ? 'V = ?·π' : `V = ${coefText(S.coef)}π`, 22, bandH + 44);
    if (!S.calib) {
      ctx.fillStyle = INK_HEX;
      const line =
        rg.kind === 'rect'
          ? `from π·${rg.w}²·${rg.h}`
          : rg.kind === 'tri'
            ? `from ⅓·π·${rg.w}²·${rg.h}`
            : `from 4/3·π·${rg.r}³`;
      ctx.fillText(line, 22, bandH + 62);
    }

    /* ---- the readout band ---- */
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillStyle = CARMINE;
    ctx.font = '700 14.5px ui-monospace, monospace';
    ctx.fillText(S.bandLabel, W / 2, bandH / 2);
  }, []);

  useEffect(() => {
    draw();
  });

  useEffect(() => {
    const stage = stageRef.current;
    if (!stage || typeof ResizeObserver === 'undefined') return;
    const ro = new ResizeObserver(() => draw());
    ro.observe(stage);
    return () => ro.disconnect();
  }, [draw]);

  /* every step opens on the scene its words describe */
  useEffect(() => {
    setWDial(3);
    setSPick(null);
    setCPick(null);
    if (STEPS[step].calib) setKase(makeCase(null));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [step]);

  const choose = (idx) => {
    if (answers[step] != null) return;
    setAnswers((prev) => ({ ...prev, [step]: idx }));
  };
  const goNext = () => setStep((s) => Math.min(STEPS.length - 1, s + 1));
  const goBack = () => setStep((s) => Math.max(0, s - 1));
  const reset = () => {
    setWDial(3);
    setSPick(null);
    setCPick(null);
  };

  const answered = answers[step] != null;
  const hasQuestion = !!current.q;
  const canNext = step < STEPS.length - 1 && (!hasQuestion || answered);

  /* accessibility — the spoken summary for screen readers */
  const spoken = calib
    ? `The stamp: ${kase != null ? labelOf(kase) : ''}. Solid ${sPick ?? 'unruled'}; coefficient ${cPick ?? 'unruled'}. ${calibrated ? 'Calibrated.' : ''}`
    : `${regionText(region)} spins into the ${solid}; the volume is ${coefText(coef)} pi.`;

  return (
    <div className="rvlab">
      <header className="head">
        <h1>Solids of Revolution: The Lathe</h1>
        <p className="lede">
          One axis, one spin: the rectangle births the cylinder, the right
          triangle the cone, the half-disc the sphere — three benches’ worth of
          solids from one move, with every volume kept as an exact coefficient
          of π. <em>Distance from the axis is the loudest dimension</em>.
        </p>
      </header>

      <div className="bench">
        {/* ---------- STAGE ---------- */}
        <section className="panel stage-panel">
          <div className="stage" ref={stageRef} role="img" aria-label={spoken}>
            <canvas ref={canvasRef} />
          </div>
          <p className="sr-only" aria-live="polite">
            {spoken}
          </p>

          {current.dial && !calib && (
            <div className="dials">
              <div className="dial">
                <div className="dial-head">
                  <span className="dial-k">the rectangle’s width</span>
                  <span className="dial-v mono">{wDial}</span>
                </div>
                <input
                  type="range"
                  min={1}
                  max={5}
                  step={1}
                  value={wDial}
                  onChange={(e) => setWDial(Number(e.target.value))}
                  aria-label={`Width, ${wDial}`}
                />
              </div>
            </div>
          )}

          <div className="toolbar" role="group" aria-label="Scene">
            <button type="button" className="btn ghost" onClick={reset}>
              Reset
            </button>
          </div>
        </section>

        {/* ---------- TUTOR ---------- */}
        <aside className="panel tutor">
          <div className="progress" role="list" aria-label="Lesson progress">
            {STEPS.map((_, i) => (
              <span
                key={i}
                role="listitem"
                className={'pip' + (i === step ? ' cur' : '') + (i < step ? ' done' : '')}
                aria-current={i === step ? 'step' : undefined}
              />
            ))}
          </div>

          <p className="eyebrow small">
            Step {step + 1} of {STEPS.length}
          </p>
          <h2>{current.title}</h2>
          <p className="body">{current.body}</p>

          {hasQuestion && (
            <div className="quiz">
              <p className="q">{current.q}</p>
              <div className="choices">
                {current.choices.map((cq, i) => {
                  const chosen = answers[step];
                  const isChosen = chosen === i;
                  const isCorrect = i === current.answer;
                  let cls = 'choice';
                  if (chosen != null) {
                    if (isCorrect) cls += ' correct';
                    else if (isChosen) cls += ' wrong';
                    else cls += ' dim';
                  }
                  return (
                    <button type="button" key={i} className={cls} onClick={() => choose(i)} disabled={chosen != null}>
                      <span className="mark" aria-hidden="true">
                        {chosen != null && isCorrect ? '✓' : chosen != null && isChosen ? '✕' : ''}
                      </span>
                      {cq}
                    </button>
                  );
                })}
              </div>
              {answered && <p className="feedback">{current.feedback}</p>}
              {answered && current.note && <p className="note">{current.note}</p>}
            </div>
          )}

          {calib && kase != null && (
            <div className="calib">
              <div className="target-card">
                <span className="target-k">The posted region</span>
                <span className="target-word">{labelOf(kase)}</span>
                <ol className="tasks">
                  <li className={checks[0] ? 'done' : ''}>{checks[0] ? '✓' : '·'} the solid, born</li>
                  <li className={checks[1] ? 'done' : ''}>{checks[1] ? '✓' : '·'} the manifest, ruled</li>
                </ol>
                <div className="declare" role="group" aria-label="Solid ruling">
                  {SOLID_CHIPS.map((c2) => (
                    <button
                      type="button"
                      key={c2}
                      className={'declbtn reason' + (sPick === c2 ? ' active' : '')}
                      onClick={() => setSPick(c2)}
                    >
                      {c2}
                    </button>
                  ))}
                </div>
                <div className="declare" role="group" aria-label="Coefficient ruling">
                  {COEF_CHIPS.map((c2) => (
                    <button
                      type="button"
                      key={c2}
                      className={'declbtn reason' + (cPick === c2 ? ' active' : '')}
                      onClick={() => setCPick(c2)}
                    >
                      {c2}π
                    </button>
                  ))}
                </div>
                <span className="target-hint mono">
                  {calibrated
                    ? 'both ruled, exactly — the lathe stops'
                    : checks[0]
                      ? 'solid born — now bill it in π'
                      : 'read the region’s kind first'}
                </span>
              </div>
              <div className="meter" aria-hidden="true">
                <div className="meter-fill" style={{ width: pct.toFixed(0) + '%' }} />
              </div>
              <div className="meter-row">
                <span className="mono">{checks.filter(Boolean).length}/2</span>
                {calibrated ? (
                  <span className="stamp">CALIBRATED</span>
                ) : (
                  <span className="mono target-hint">the solid · then the coefficient</span>
                )}
              </div>
              <button
                type="button"
                className="btn ghost"
                onClick={() => {
                  setKase(makeCase(kase));
                  setSPick(null);
                  setCPick(null);
                }}
              >
                Next case
              </button>
            </div>
          )}

          <div className="nav">
            <button type="button" className="btn ghost" onClick={goBack} disabled={step === 0}>
              ← Back
            </button>
            {step < STEPS.length - 1 ? (
              <button type="button" className="btn" onClick={goNext} disabled={!canNext}>
                {hasQuestion && !answered ? 'Answer to continue' : 'Next →'}
              </button>
            ) : (
              <button
                type="button"
                className="btn"
                onClick={() => {
                  setStep(0);
                  setAnswers({});
                  setKase(null);
                  setSPick(null);
                  setCPick(null);
                }}
              >
                Restart lab
              </button>
            )}
          </div>
        </aside>
      </div>

      <footer className="foot">
        <span className="mono">rectangle → cylinder · triangle → cone · half-disc → sphere</span>{' '}
        &nbsp;·&nbsp; one axis, one spin, exact bills in π — and Archimedes’ 2/3
        carved where it belongs.
      </footer>

      <style jsx>{`
        .rvlab {
          --page: #eff1ee;
          --paper: #fbfbf8;
          --ink: #1c2b3a;
          --ink-soft: #5b6b7b;
          --carmine: #c81e4f;
          --blue: #3f74a6;
          --gold: #b98718;
          --quad: #c7d8e4;
          --ok: #1f8a5b;
          --mono: ui-monospace, 'SF Mono', SFMono-Regular, Menlo, Consolas, monospace;
          --serif: 'Iowan Old Style', 'Palatino Linotype', Palatino, Georgia, serif;
          background: var(--page);
          color: var(--ink);
          font: 16px/1.55 system-ui, -apple-system, 'Segoe UI', sans-serif;
          padding: 28px 18px 44px;
          border-radius: 16px;
          max-width: 1120px;
          margin: 0 auto;
        }
        .mono {
          font-family: var(--mono);
        }
        .sr-only {
          position: absolute;
          width: 1px;
          height: 1px;
          padding: 0;
          margin: -1px;
          overflow: hidden;
          clip: rect(0, 0, 0, 0);
          white-space: nowrap;
          border: 0;
        }
        .eyebrow {
          font-size: 11px;
          letter-spacing: 0.24em;
          text-transform: uppercase;
          color: var(--ink-soft);
          margin: 0 0 6px;
        }
        .eyebrow.small {
          margin: 0 0 4px;
        }
        h1 {
          font-family: var(--serif);
          font-weight: 600;
          font-size: clamp(26px, 4vw, 34px);
          margin: 0 0 6px;
        }
        .lede {
          color: var(--ink-soft);
          margin: 0 0 22px;
          max-width: 72ch;
        }
        .lede em {
          font-style: italic;
          color: var(--ink);
        }
        .bench {
          display: grid;
          grid-template-columns: minmax(0, 1fr) 340px;
          gap: 22px;
          align-items: start;
        }
        @media (max-width: 920px) {
          .bench {
            grid-template-columns: minmax(0, 1fr);
          }
        }
        .panel {
          min-width: 0;
          background: #fff;
          border: 1px solid rgba(28, 43, 58, 0.15);
          border-radius: 12px;
          box-shadow: 0 1px 2px rgba(28, 43, 58, 0.05);
        }
        .stage-panel {
          padding: 14px;
        }
        .stage {
          position: relative;
          width: 100%;
          aspect-ratio: 7 / 5;
          min-height: 400px;
          margin: 0 auto;
          border: 1px solid var(--quad);
          border-radius: 8px;
          overflow: hidden;
          touch-action: none;
          background: linear-gradient(180deg, #fdfefe 0%, #f4f7f9 100%);
        }
        .stage canvas {
          display: block;
          width: 100%;
          height: 100%;
        }
        @media (max-width: 560px) {
          .stage {
            aspect-ratio: 4 / 5;
            min-height: 380px;
          }
        }
        .dials {
          margin: 12px 4px 0;
          display: grid;
          gap: 8px;
        }
        .dial {
          padding: 8px 10px;
          border: 1px solid rgba(28, 43, 58, 0.14);
          border-radius: 8px;
          background: var(--paper);
        }
        .dial-head {
          display: flex;
          justify-content: space-between;
          align-items: baseline;
          margin-bottom: 4px;
        }
        .dial-k {
          font-size: 12.5px;
          font-weight: 600;
        }
        .dial-v {
          font-size: 13px;
          color: var(--gold);
          font-weight: 700;
        }
        .dial input[type='range'] {
          width: 100%;
          accent-color: var(--gold);
        }
        .toolbar {
          margin: 12px 4px 2px;
          display: flex;
          gap: 8px;
          flex-wrap: wrap;
          align-items: center;
        }
        .chipbtn {
          font: 600 12px/1.2 system-ui, sans-serif;
          padding: 8px 11px;
          border-radius: 8px;
          cursor: pointer;
          border: 1.5px solid rgba(63, 116, 166, 0.55);
          background: var(--paper);
          color: var(--blue);
          transition: border-color 0.15s, background 0.15s;
        }
        .chipbtn.active {
          border-color: var(--blue);
          background: rgba(63, 116, 166, 0.1);
        }
        .chipbtn:hover {
          border-color: var(--ink);
        }
        .btn {
          font: 600 13px/1 system-ui, sans-serif;
          padding: 9px 14px;
          border-radius: 8px;
          cursor: pointer;
          border: 1px solid var(--ink);
          background: var(--ink);
          color: #fff;
          transition: background 0.15s, color 0.15s, border-color 0.15s, opacity 0.15s;
        }
        .btn.ghost {
          background: transparent;
          color: var(--ink);
        }
        .btn:disabled {
          opacity: 0.4;
          cursor: not-allowed;
        }
        .btn:not(:disabled):hover {
          filter: brightness(1.08);
        }
        .tutor {
          padding: 18px 20px 20px;
        }
        .progress {
          display: flex;
          gap: 6px;
          margin-bottom: 14px;
        }
        .pip {
          height: 5px;
          flex: 1;
          border-radius: 3px;
          background: rgba(28, 43, 58, 0.14);
        }
        .pip.done {
          background: rgba(200, 30, 79, 0.45);
        }
        .pip.cur {
          background: var(--carmine);
        }
        h2 {
          font-family: var(--serif);
          font-weight: 600;
          font-size: 20px;
          margin: 0 0 10px;
          padding-bottom: 9px;
          border-bottom: 3px double rgba(200, 30, 79, 0.45);
        }
        .body {
          margin: 0 0 16px;
          font-size: 14.5px;
        }
        .quiz {
          margin-top: 4px;
          padding-top: 6px;
        }
        .q {
          font-size: 14px;
          font-weight: 600;
          margin: 0 0 10px;
        }
        .choices {
          display: grid;
          gap: 7px;
        }
        .choice {
          text-align: left;
          font: 13.5px/1.4 system-ui, sans-serif;
          padding: 9px 11px 9px 30px;
          border: 1px solid rgba(28, 43, 58, 0.2);
          border-radius: 8px;
          background: var(--paper);
          color: var(--ink);
          cursor: pointer;
          position: relative;
          transition: border-color 0.15s, background 0.15s;
        }
        .choice:not(:disabled):hover {
          border-color: var(--ink);
        }
        .choice .mark {
          position: absolute;
          left: 10px;
          font-weight: 700;
        }
        .choice.correct {
          border-color: var(--ok);
          background: rgba(31, 138, 91, 0.08);
        }
        .choice.correct .mark {
          color: var(--ok);
        }
        .choice.wrong {
          border-color: var(--ink-soft);
          background: rgba(91, 107, 123, 0.08);
        }
        .choice.wrong .mark {
          color: var(--ink-soft);
        }
        .choice.dim {
          opacity: 0.55;
        }
        .choice:disabled {
          cursor: default;
        }
        .feedback {
          margin: 12px 0 0;
          font-size: 13px;
          line-height: 1.55;
          color: var(--ink);
          background: rgba(200, 30, 79, 0.05);
          border-left: 3px solid var(--carmine);
          padding: 10px 12px;
          border-radius: 0 6px 6px 0;
        }
        .calib {
          margin-top: 16px;
          padding-top: 14px;
          border-top: 1px solid rgba(28, 43, 58, 0.1);
          display: grid;
          gap: 10px;
        }
        .target-card {
          display: flex;
          flex-direction: column;
          gap: 6px;
          padding: 10px 12px;
          border: 1px solid rgba(28, 43, 58, 0.16);
          border-radius: 8px;
          background: rgba(185, 135, 24, 0.07);
        }
        .target-k {
          font-size: 11px;
          letter-spacing: 0.08em;
          text-transform: uppercase;
          color: var(--ink-soft);
        }
        .target-word {
          font-family: var(--serif);
          font-size: 21px;
          font-weight: 600;
        }
        .tasks {
          margin: 0;
          padding: 0 0 0 4px;
          list-style: none;
          font-size: 13.5px;
          display: grid;
          gap: 4px;
        }
        .tasks li.done {
          color: var(--ok);
          font-weight: 600;
        }
        .declare {
          display: flex;
          gap: 6px;
          flex-wrap: wrap;
        }
        .declbtn {
          font-size: 12.5px;
          font-weight: 700;
          padding: 7px 11px;
          border-radius: 6px;
          cursor: pointer;
          border: 1.5px solid rgba(28, 43, 58, 0.28);
          background: var(--paper);
          color: var(--ink);
        }
        .declbtn.reason {
          font-size: 11.5px;
          font-weight: 600;
        }
        .declbtn.active {
          border-color: var(--carmine);
          background: rgba(200, 30, 79, 0.1);
          color: var(--carmine);
        }
        .target-hint {
          color: var(--ink-soft);
          font-size: 12px;
        }
        .meter {
          height: 12px;
          border-radius: 6px;
          background: rgba(28, 43, 58, 0.1);
          overflow: hidden;
        }
        .meter-fill {
          height: 100%;
          background: linear-gradient(90deg, rgba(200, 30, 79, 0.55), var(--carmine));
          transition: width 0.12s ease-out;
        }
        .meter-row {
          display: flex;
          justify-content: space-between;
          align-items: center;
          gap: 8px;
          font-size: 13px;
        }
        .stamp {
          font: 700 12px/1 var(--mono);
          letter-spacing: 0.16em;
          color: var(--ok);
          border: 2px solid var(--ok);
          border-radius: 6px;
          padding: 4px 8px;
          transform: rotate(-3deg);
          white-space: nowrap;
        }
        .nav {
          margin-top: 20px;
          display: flex;
          justify-content: space-between;
          gap: 10px;
        }
        .foot {
          margin-top: 24px;
          font-size: 12.5px;
          color: var(--ink-soft);
        }
        :global(.rvlab) :focus-visible {
          outline: 2px solid var(--ink);
          outline-offset: 2px;
          border-radius: 4px;
        }
        @media (max-width: 460px) {
          .toolbar {
            gap: 6px;
          }
        }
        @media (prefers-reduced-motion: reduce) {
          .btn,
          .meter-fill,
          .choice,
          .chipbtn {
            transition: none;
          }
        }
      `}</style>
    </div>
  );
}
