import type { AuthUserStore } from "./domainContracts";
import {
  authenticateFlexibleExampleAccountForLogin,
  authenticatedUserForCredentials,
  authenticateUser,
  authenticateUserForLogin,
  backfillPostgresHotAuthTablesForAdmin,
  buildRedactedAdminStorageSnapshot,
  changeAuthenticatedUserPassword,
  cleanupTemporaryBootstrapAdminsForAdmin,
  completeStudentCurriculumTrackSelection,
  createParentUser,
  createPasswordResetRequest,
  createSchoolProvisioningBatch,
  createStudentUser,
  createTeacherUser,
  exportDatabaseSnapshotForAdmin,
  getAuthenticatedUserById,
  getAuthenticatedUserByIdForAiTutorAdmission,
  getLearnerProfile,
  getProvisioningBatchCredentialCsvForAdmin,
  getProvisioningBatchForAdmin,
  getStorageReadinessSnapshot,
  isGradeAllowedForCurriculumProfile,
  resetUserPassword,
  shouldRetryDemoLoginAfterFastInvalid,
  updateLearnerProfile,
  updateUserProfile,
  updateUserSettings,
  validateSchoolProvisioning
} from "../userStore";

export type { AuthUserStore } from "./domainContracts";

export {
  authenticateFlexibleExampleAccountForLogin,
  authenticatedUserForCredentials,
  authenticateUser,
  authenticateUserForLogin,
  backfillPostgresHotAuthTablesForAdmin,
  buildRedactedAdminStorageSnapshot,
  changeAuthenticatedUserPassword,
  cleanupTemporaryBootstrapAdminsForAdmin,
  completeStudentCurriculumTrackSelection,
  createParentUser,
  createPasswordResetRequest,
  createSchoolProvisioningBatch,
  createStudentUser,
  createTeacherUser,
  exportDatabaseSnapshotForAdmin,
  getAuthenticatedUserById,
  getAuthenticatedUserByIdForAiTutorAdmission,
  getLearnerProfile,
  getProvisioningBatchCredentialCsvForAdmin,
  getProvisioningBatchForAdmin,
  getStorageReadinessSnapshot,
  isGradeAllowedForCurriculumProfile,
  resetUserPassword,
  shouldRetryDemoLoginAfterFastInvalid,
  updateLearnerProfile,
  updateUserProfile,
  updateUserSettings,
  validateSchoolProvisioning
};

export const authUserStore = {
  isGradeAllowedForCurriculumProfile,
  shouldRetryDemoLoginAfterFastInvalid,
  authenticatedUserForCredentials,
  authenticateUser,
  authenticateUserForLogin,
  authenticateFlexibleExampleAccountForLogin,
  createStudentUser,
  createTeacherUser,
  createParentUser,
  completeStudentCurriculumTrackSelection,
  validateSchoolProvisioning,
  createSchoolProvisioningBatch,
  getProvisioningBatchForAdmin,
  getProvisioningBatchCredentialCsvForAdmin,
  changeAuthenticatedUserPassword,
  createPasswordResetRequest,
  resetUserPassword,
  getAuthenticatedUserById,
  getAuthenticatedUserByIdForAiTutorAdmission,
  buildRedactedAdminStorageSnapshot,
  exportDatabaseSnapshotForAdmin,
  backfillPostgresHotAuthTablesForAdmin,
  cleanupTemporaryBootstrapAdminsForAdmin,
  getStorageReadinessSnapshot,
  updateUserSettings,
  updateUserProfile,
  getLearnerProfile,
  updateLearnerProfile
} satisfies AuthUserStore;
