"use client";

import { useState } from "react";
import { MathCheck } from "@/components/lesson/ccss/MathCheck";
import { Figure } from "@/components/lesson/ccss/Figure";

const ACCENT = "var(--band-high)";
const CTRL = "var(--band-upper)";

export default function Lesson() {
  const [diff, setDiff] = useState(8); // observed difference in means
  const [threshold] = useState(5); // significance cutoff from simulation

  const significant = diff >= threshold;

  return (
    <div className="prose-lesson max-w-none">
      <p>
        Does a new fertilizer really help, or did the treated plants just get lucky? A{" "}
        <strong>randomized experiment</strong>{" "}compares two groups, then asks whether
        the observed difference is <strong>bigger than random chance alone</strong>{" "}
        would typically produce.
      </p>

      <Figure caption="Compare treatment vs control. A difference beyond what re-randomization produces is significant.">
        <div className="flex flex-col items-center gap-6">
          <div className="flex items-end gap-8">
            <Bar label="Control" value={30} color={CTRL} />
            <Bar label="Treatment" value={30 + diff} color={ACCENT} />
          </div>

          <div className="rounded-2xl border-2 px-6 py-3 text-center" style={{ borderColor: significant ? ACCENT : "var(--ink-soft)" }}>
            <div className="font-mono">observed difference = <strong style={{ color: ACCENT }}>{diff}</strong></div>
            <div className="mt-1 text-sm font-bold" style={{ color: significant ? ACCENT : "var(--ink-soft)" }}>
              {significant
                ? `Larger than the ${threshold} that chance re-randomization usually produces → significant.`
                : `Within the range chance alone can produce (≤ ${threshold}) → not significant.`}
            </div>
          </div>

          <Stepper label="observed difference" value={diff} min={0} max={15} onChange={setDiff} />
        </div>
      </Figure>

      <h2>Is it more than chance?</h2>
      <p>
        Randomly shuffle which plants are labeled "treatment" and recompute the
        difference — many times. That builds a distribution of differences that{" "}
        <em>chance</em>{" "}produces. If the real difference ({diff}) sits far out in that
        distribution (beyond ~{threshold} here), it&apos;s unlikely to be luck, so we
        conclude the treatment had a real effect.
      </p>

      <MathCheck>
        <p>
          A <strong>randomized experiment</strong>{" "}compares two treatments (S-IC.5);
          random assignment balances lurking variables so a difference can be
          attributed to the treatment. To judge significance, compare the observed
          difference to the distribution of differences generated by{" "}
          <strong>re-randomization</strong>{" "}— a difference far in the tail is
          statistically significant.
        </p>
      </MathCheck>
    </div>
  );
}

function Bar({ label, value, color }: { label: string; value: number; color: string }) {
  return (
    <div className="flex flex-col items-center gap-1">
      <div className="w-16 rounded-t" style={{ height: value * 4, background: color }} />
      <span className="text-xs font-bold" style={{ color }}>{label}</span>
      <span className="font-mono text-sm">{value}</span>
    </div>
  );
}

function Stepper({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (n: number) => void }) {
  return (
    <div className="flex flex-col items-center gap-1">
      <span className="text-xs font-semibold uppercase tracking-wide text-[var(--ink-faint)]">{label}</span>
      <div className="flex items-center gap-2">
        <button type="button" onClick={() => onChange(Math.max(min, value - 1))} disabled={value <= min} className="h-9 w-9 rounded-lg border border-[var(--line)] bg-[var(--surface)] text-lg font-bold disabled:opacity-40" aria-label={`Decrease ${label}`}>−</button>
        <span className="w-8 text-center text-2xl font-black tabular-nums" style={{ color: ACCENT }}>{value}</span>
        <button type="button" onClick={() => onChange(Math.min(max, value + 1))} disabled={value >= max} className="h-9 w-9 rounded-lg border border-[var(--line)] bg-[var(--surface)] text-lg font-bold disabled:opacity-40" aria-label={`Increase ${label}`}>+</button>
      </div>
    </div>
  );
}
