"use client";

import { useState } from "react";
import { MathCheck } from "@/components/lesson/ccss/MathCheck";
import { Figure } from "@/components/lesson/ccss/Figure";

const ACCENT = "var(--band-high)";

const CASES = [
  { name: "Cube, flat slice", result: "square", shape: "square" },
  { name: "Cube, diagonal slice", result: "rectangle / hexagon", shape: "hex" },
  { name: "Cylinder, vertical slice", result: "rectangle", shape: "rect" },
  { name: "Cone, horizontal slice", result: "circle", shape: "circle" },
];

const ROTATIONS = [
  { name: "Rectangle → cylinder", desc: "Spin a rectangle about one edge and it sweeps out a cylinder." },
  { name: "Right triangle → cone", desc: "Spin a right triangle about a leg and it sweeps out a cone." },
  { name: "Semicircle → sphere", desc: "Spin a semicircle about its diameter and it sweeps out a sphere." },
];

export default function Lesson() {
  const [idx, setIdx] = useState(0);
  const [rot, setRot] = useState(0);
  const c = CASES[idx];

  return (
    <div className="prose-lesson max-w-none">
      <p>
        Two ways to connect 2-D and 3-D. A <strong>cross-section</strong>{" "}is the
        shape you see when you slice a solid. A <strong>solid of revolution</strong>{" "}
        is what you get by spinning a 2-D region around an axis.
      </p>

      <Figure caption="Slicing a solid reveals a 2-D cross-section; spinning a 2-D shape sweeps out a 3-D solid.">
        <div className="flex flex-col items-center gap-6">
          <div className="flex flex-wrap justify-center gap-2">
            {CASES.map((ca, i) => (
              <button key={ca.name} type="button" onClick={() => setIdx(i)} className="rounded-lg border px-3 py-1.5 text-xs font-bold" style={idx === i ? { background: ACCENT, color: "white", borderColor: ACCENT } : { borderColor: "var(--line)", color: "var(--ink-soft)" }}>{ca.name}</button>
            ))}
          </div>

          <svg width={160} height={140} viewBox="0 0 160 140" role="img" aria-label={`${c.name}: the cross-section drawn is ${c.shape === "hex" ? "a hexagon" : `a ${c.result}`}`}>
            {c.shape === "square" && <rect x={45} y={35} width={70} height={70} fill={ACCENT} fillOpacity={0.3} stroke={ACCENT} strokeWidth={2.5} />}
            {c.shape === "rect" && <rect x={35} y={30} width={90} height={80} fill={ACCENT} fillOpacity={0.3} stroke={ACCENT} strokeWidth={2.5} />}
            {c.shape === "circle" && <circle cx={80} cy={70} r={42} fill={ACCENT} fillOpacity={0.3} stroke={ACCENT} strokeWidth={2.5} />}
            {c.shape === "hex" && <polygon points="80,25 125,50 125,95 80,120 35,95 35,50" fill={ACCENT} fillOpacity={0.3} stroke={ACCENT} strokeWidth={2.5} />}
          </svg>
          <div className="text-sm font-bold" style={{ color: ACCENT }}>cross-section: {c.result}</div>

          <div className="w-full max-w-md border-t border-[var(--line)] pt-4">
            <div className="mb-2 text-center text-xs font-bold uppercase text-[var(--ink-faint)]">solids of revolution</div>
            <div className="flex flex-wrap justify-center gap-2">
              {ROTATIONS.map((ro, i) => (
                <button key={ro.name} type="button" onClick={() => setRot(i)} className="rounded-lg border px-3 py-1.5 text-xs font-bold" style={rot === i ? { background: "var(--band-upper)", color: "white", borderColor: "var(--band-upper)" } : { borderColor: "var(--line)", color: "var(--ink-soft)" }}>{ro.name}</button>
              ))}
            </div>
            <p className="m-0 mt-2 text-center text-sm text-[var(--ink-soft)]">{ROTATIONS[rot].desc}</p>
          </div>
        </div>
      </Figure>

      <h2>Slicing and spinning</h2>
      <p>
        Slice a cube parallel to a face and you get a square; slice it at an angle and
        you can get a rectangle or even a hexagon. Spin a flat region and it sweeps a
        solid — a <strong>rectangle becomes a cylinder</strong>, a right triangle a
        cone, a semicircle a sphere. Both viewpoints link plane and space geometry.
      </p>

      <MathCheck>
        <p>
          Identifying the <strong>two-dimensional cross-sections</strong>{" "}of
          three-dimensional objects, and the <strong>three-dimensional solids
          generated by rotating</strong>{" "}two-dimensional shapes about an axis
          (G-GMD.4). Slicing reveals hidden structure; revolution builds cylinders,
          cones, and spheres from simple regions.
        </p>
      </MathCheck>
    </div>
  );
}
