import type { Topic } from "@/types";
import topicsMetadataJson from "./generated-content/topics-metadata/topics-metadata.json";

/**
 * Client-safe snapshot of the aggregated `topics` metadata (see @/data/topics).
 *
 * `@/data/topics` derives its `Topic[]` from the per-region topic modules, each of which
 * statically imports its multi-MB question-bank JSON. Importing `@/data/topics` from a
 * client component therefore ships tens of MB of question banks to the browser. Client
 * code that only needs topic metadata (roadmaps, directories) must import THIS module
 * instead — it carries the derived metadata only, no question banks.
 *
 * The snapshot is generated by `scripts/generate-topics-metadata.mts`; if it drifts from
 * the live `topics`, `data/topicsMetadata.test.ts` fails with the regenerate command.
 */
export const topicsMetadata = topicsMetadataJson as unknown as Topic[];
