/**
 * audit-ccss-depth.ts
 *
 * Scores every CCSS-M standard by the DEPTH of the visualization it can actually
 * reach — not merely whether some lab's `standardIds` array names it.
 *
 * Usage:
 *   npm run audit:ccss-depth                 # the summary tables
 *   npm run audit:ccss-depth -- --json       # machine-readable, all 385 rows
 *   npm run audit:ccss-depth -- --csv out.csv
 *   npm run audit:ccss-depth -- --library "/path/to/Claude Math Visual"
 *
 * WHY THIS EXISTS
 * ---------------
 * The 2026-07-25 depth audit found that a coverage number built from
 * `standardIds` was badly misleading: 78% of California labs get their alignment
 * from a WHOLE-DOMAIN AUTO-FILL in `californiaAlignmentForTopic`, so a lab claims
 * every standard in its domain whether or not anything on the screen teaches
 * them. "94% covered" was mostly that fallback.
 *
 * This scorer answers the question that actually matters — *can a student reach a
 * visual whose subject is this standard?* — by asking what renders, not what is
 * listed. `scripts/ccssDepthCoverage.test.ts` turns its output into a CI gate so
 * the coverage cannot quietly regress.
 *
 * THE TIERS
 * ---------
 *   A  Dedicated bench   a bench tagged to <= 3 standards (including this one) is
 *                        primary or related on a topic that carries it
 *   B  Shared bench      same, but the bench is tagged to 4+ standards
 *   C  Curated template  no bench; the claiming lab's alignment was curated
 *                        (explicit or cluster-scoped), not auto-filled
 *   D  Incidental        no bench; the only claim came from the whole-domain
 *                        auto-fill — the standard is named, not necessarily taught
 *   E  Untracked         no lab alignment names it, but a reachable bench's own
 *                        CCSS tags cover it (routed to another grade band)
 *   F  Absent            no lab names it and no reachable bench teaches it
 *
 * "Real visual" = A + B + E.  "Paper only" = D + F.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { grades } from "@/data/ccss";
import { visualizationLabCatalog } from "@/data/visualizationLabs";
import { signatureLabAssignments } from "@/data/signatureLabAssignments";
import { signatureLabCcssOverrides } from "@/data/signatureLabCcssOverrides";

export type DepthTier = "A" | "B" | "C" | "D" | "E" | "F";

export type DepthRow = {
  id: string;
  grade: string;
  band: string;
  domain: string;
  domainName: string;
  cluster: string;
  description: string;
  tier: DepthTier;
  instrument: string;
  evidence: string;
  reachability: string;
  hostLabId: string | null;
  hostLabTitle: string | null;
  bench: string | null;
  labsClaiming: number;
};

export type DepthReport = {
  rows: DepthRow[];
  totals: Record<DepthTier, number>;
  byGrade: { grade: string; n: number; tiers: Record<DepthTier, number>; realVisual: number; paperOnly: number }[];
  benchesPorted: number;
  benchesReachable: number;
  benchesOrphaned: number;
  labsWholeDomain: number;
  labsTotal: number;
};

const GRADE_ORDER = ["K", "1", "2", "3", "4", "5", "6", "7", "8", "HS"];
const DEFAULT_LIBRARY = join(process.env.HOME ?? "", "Desktop", "Claude Math Visual");

/** Re-exported so the coverage test can probe for the library without duplicating the path. */
export const DEFAULT_LIBRARY_FOR_TESTS = DEFAULT_LIBRARY;

/**
 * Normalise CCSS ids so the two libraries agree — the same rule as
 * `build-signature-lab-candidates.ts`. MAIS emits "6.NS.7"; the Claude library
 * emits "6.NS.C.7c". Drop the cluster letter and any sub-letter.
 */
export function normalizeCcss(code: string): string {
  const highSchool = code.match(/^([A-Z]+)-([A-Z]+)\.([A-Z])\.(\d+)/);
  if (highSchool) return `${highSchool[1]}-${highSchool[2]}.${highSchool[4]}`;
  const k12 = code.match(/^(K|\d+)\.([A-Z]+)(?:\.([A-Z]))?\.(\d+)/);
  if (k12) return `${k12[1]}.${k12[2]}.${k12[4]}`;
  return code;
}

type BenchMeta = { ccss?: string[] };

/**
 * The committed snapshot of the merged bench → standards table.
 *
 * The upstream `labs.json` lives OUTSIDE the repo (on the author's Desktop), so a
 * CI gate cannot read it. This snapshot is the same table, generated by
 * `--write-snapshot`, and it is what the regression test consumes so the gate
 * runs anywhere. Refresh it whenever the upstream library's CCSS tags change:
 *
 *     npm run audit:ccss-depth -- --write-snapshot
 */
export const SNAPSHOT_PATH = join(
  process.cwd(),
  "data/generated-content/ccss-depth/bench-standards.json"
);

/** Read the upstream bench metadata and merge the MAIS-side supplemental tags. */
export function loadBenchStandards(library = DEFAULT_LIBRARY): Map<string, Set<string>> {
  const labs = JSON.parse(readFileSync(join(library, "labs.json"), "utf8")) as Record<string, BenchMeta>;
  const out = new Map<string, Set<string>>();
  for (const [name, meta] of Object.entries(labs)) {
    out.set(name, new Set((meta.ccss ?? []).map(normalizeCcss)));
  }
  for (const [name, codes] of Object.entries(signatureLabCcssOverrides)) {
    const set = out.get(name) ?? new Set<string>();
    for (const code of codes) set.add(normalizeCcss(code));
    out.set(name, set);
  }
  return out;
}

/** Is the upstream library readable on this machine? */
export function libraryAvailable(library = DEFAULT_LIBRARY): boolean {
  try {
    readFileSync(join(library, "labs.json"), "utf8");
    return true;
  } catch {
    return false;
  }
}

export function readSnapshot(path = SNAPSHOT_PATH): Map<string, Set<string>> {
  const raw = JSON.parse(readFileSync(path, "utf8")) as { benches: Record<string, string[]> };
  return new Map(Object.entries(raw.benches).map(([name, codes]) => [name, new Set(codes)]));
}

export function writeSnapshot(table: Map<string, Set<string>>, path = SNAPSHOT_PATH): void {
  const benches: Record<string, string[]> = {};
  for (const name of [...table.keys()].sort()) benches[name] = [...table.get(name)!].sort();
  writeFileSync(
    path,
    `${JSON.stringify(
      {
        note:
          "Generated by scripts/audit-ccss-depth.ts --write-snapshot. The upstream " +
          "labs.json lives outside the repo, so this committed copy is what the CI " +
          "coverage gate reads. Do not hand-edit; regenerate.",
        generatedAt: new Date().toISOString().slice(0, 10),
        benches,
      },
      null,
      2
    )}\n`
  );
}

/**
 * The table the audit should use: the live library when it is available (so a
 * developer always sees current truth), otherwise the committed snapshot.
 */
export function resolveBenchStandards(library = DEFAULT_LIBRARY): Map<string, Set<string>> {
  return libraryAvailable(library) ? loadBenchStandards(library) : readSnapshot();
}

/** Score every canonical standard. Pure — takes the bench table, returns rows. */
export function scoreCcssDepth(benchStandards: Map<string, Set<string>>): DepthReport {
  /* --- the canonical registry ------------------------------------------- */
  const canonical = grades.flatMap((g) =>
    g.domains.flatMap((d) =>
      d.clusters.flatMap((c) =>
        c.standards.map((s) => ({
          id: s.id,
          description: s.description,
          grade: g.id as string,
          band: g.band as string,
          domainCode: d.code,
          domainName: d.name,
          clusterHeading: c.heading,
        }))
      )
    )
  );

  /* every standard in a domain, keyed the way a lab's domainId is written:
     "6.RP" for K-8, "A-CED" for high school */
  const domainFull = new Map<string, Set<string>>();
  for (const s of canonical) {
    const key = s.grade === "HS" ? s.domainCode : `${s.grade}.${s.domainCode}`;
    if (!domainFull.has(key)) domainFull.set(key, new Set());
    domainFull.get(key)!.add(normalizeCcss(s.id));
  }

  /* --- the California labs, annotated ------------------------------------ */
  type Lab = {
    labId: string;
    topicId: string;
    grade: string;
    title: string;
    templateId: string;
    claim: Set<string>;
    fanOut: number;
    wholeDomain: boolean;
    domainCode: string;
    primary: string | null;
    related: string[];
  };
  const labs: Lab[] = visualizationLabCatalog
    .filter((lab) => lab.californiaAlignment)
    .map((lab) => {
      const assignment = signatureLabAssignments[lab.topicId] ?? null;
      const claim = new Set(lab.californiaAlignment!.standardIds.map(normalizeCcss));
      const domainCode = lab.californiaAlignment!.domainId.replace("CA.CCSS.Math.", "");
      const full = domainFull.get(domainCode);
      return {
        labId: lab.labId,
        topicId: lab.topicId,
        grade: lab.grade as string,
        title: lab.title.en,
        templateId: lab.templateId as string,
        claim,
        fanOut: claim.size,
        wholeDomain: Boolean(full) && full!.size === claim.size && [...full!].every((c) => claim.has(c)),
        domainCode,
        primary: assignment?.primary ?? null,
        related: assignment?.related ?? [],
      };
    });

  /* which benches a student can reach at all, and from where */
  const reachable = new Map<string, Lab[]>();
  for (const lab of labs) {
    for (const name of [lab.primary, ...lab.related].filter(Boolean) as string[]) {
      reachable.set(name, [...(reachable.get(name) ?? []), lab]);
    }
  }

  const labsFor = new Map<string, Lab[]>();
  for (const lab of labs) {
    for (const key of lab.claim) labsFor.set(key, [...(labsFor.get(key) ?? []), lab]);
  }
  const strayFor = new Map<string, string[]>();
  for (const name of reachable.keys()) {
    for (const key of benchStandards.get(name) ?? []) {
      strayFor.set(key, [...(strayFor.get(key) ?? []), name]);
    }
  }

  const benchFanOut = (name: string) => (benchStandards.get(name) ?? new Set()).size;

  /* --- score every standard --------------------------------------------- */
  const rows: DepthRow[] = canonical.map((s) => {
    const key = normalizeCcss(s.id);
    const hosts = labsFor.get(key) ?? [];

    /* a bench routed through a topic that actually carries this standard */
    const routed: { bench: string; role: string; lab: Lab }[] = [];
    for (const lab of hosts) {
      if (lab.primary && (benchStandards.get(lab.primary) ?? new Set()).has(key)) {
        routed.push({ bench: lab.primary, role: "renders by default", lab });
      }
      for (const name of lab.related) {
        if ((benchStandards.get(name) ?? new Set()).has(key)) {
          routed.push({ bench: name, role: "related-lab switcher", lab });
        }
      }
    }

    const base = {
      id: s.id,
      grade: s.grade,
      band: s.band,
      domain: s.domainCode,
      domainName: s.domainName,
      cluster: s.clusterHeading,
      description: s.description,
      labsClaiming: hosts.length,
    };

    if (routed.length > 0) {
      const best = routed.reduce((a, b) => {
        const rank = (r: typeof a) => [benchFanOut(r.bench), r.role === "renders by default" ? 0 : 1];
        const [af, ar] = rank(a);
        const [bf, br] = rank(b);
        return bf < af || (bf === af && br < ar) ? b : a;
      });
      return {
        ...base,
        tier: benchFanOut(best.bench) <= 3 ? "A" : "B",
        instrument: `${best.bench} bench`,
        evidence: `bench tagged to ${benchFanOut(best.bench)} standard(s)`,
        reachability: best.role,
        hostLabId: best.lab.labId,
        hostLabTitle: best.lab.title,
        bench: best.bench,
      };
    }

    if (hosts.length > 0) {
      const lab = hosts.reduce((a, b) =>
        (b.wholeDomain ? 1 : 0) < (a.wholeDomain ? 1 : 0) || (a.wholeDomain === b.wholeDomain && b.fanOut < a.fanOut)
          ? b
          : a
      );
      const diluted = lab.wholeDomain || lab.fanOut >= 7;
      return {
        ...base,
        tier: diluted ? "D" : "C",
        instrument: `${lab.templateId} template`,
        evidence: lab.wholeDomain
          ? `whole-${lab.domainCode}-domain auto-fill (${lab.fanOut} std)`
          : `curated claim, ${lab.fanOut} std`,
        reachability: "template lab",
        hostLabId: lab.labId,
        hostLabTitle: lab.title,
        bench: null,
      };
    }

    const stray = strayFor.get(key) ?? [];
    if (stray.length > 0) {
      const name = stray.reduce((a, b) => (benchFanOut(b) < benchFanOut(a) ? b : a));
      const where = [...new Set((reachable.get(name) ?? []).map((l) => l.grade))].join(", ");
      return {
        ...base,
        tier: "E",
        instrument: name,
        evidence: `a reachable bench teaches it (lives on ${where} topics) but no CA topic alignment lists the standard`,
        reachability: "reachable, untracked",
        hostLabId: (reachable.get(name) ?? [])[0]?.labId ?? null,
        hostLabTitle: (reachable.get(name) ?? [])[0]?.title ?? null,
        bench: name,
      };
    }

    return {
      ...base,
      tier: "F",
      instrument: "—",
      evidence: "no lab claims it and no reachable bench teaches it",
      reachability: "—",
      hostLabId: null,
      hostLabTitle: null,
      bench: null,
    };
  });

  const blank = (): Record<DepthTier, number> => ({ A: 0, B: 0, C: 0, D: 0, E: 0, F: 0 });
  const totals = blank();
  for (const r of rows) totals[r.tier] += 1;

  const byGrade = GRADE_ORDER.map((grade) => {
    const sub = rows.filter((r) => r.grade === grade);
    const tiers = blank();
    for (const r of sub) tiers[r.tier] += 1;
    return {
      grade,
      n: sub.length,
      tiers,
      realVisual: tiers.A + tiers.B + tiers.E,
      paperOnly: tiers.D + tiers.F,
    };
  });

  const portedNames = new Set(benchStandards.keys());
  const reachableNames = new Set(reachable.keys());

  return {
    rows,
    totals,
    byGrade,
    benchesPorted: portedNames.size,
    benchesReachable: [...reachableNames].filter((n) => portedNames.has(n)).length,
    benchesOrphaned: [...portedNames].filter((n) => !reachableNames.has(n)).length,
    labsWholeDomain: labs.filter((l) => l.wholeDomain).length,
    labsTotal: labs.length,
  };
}

/** The whole pipeline: resolve the bench table, score, return. */
export function runCcssDepthAudit(library = DEFAULT_LIBRARY): DepthReport {
  return scoreCcssDepth(resolveBenchStandards(library));
}

/* ---------------------------------------------------------------------------
   CLI
   ------------------------------------------------------------------------- */
function main() {
  const args = process.argv.slice(2);
  const libIndex = args.indexOf("--library");
  const csvIndex = args.indexOf("--csv");
  const library = libIndex >= 0 ? args[libIndex + 1] : DEFAULT_LIBRARY;

  if (args.includes("--write-snapshot")) {
    if (!libraryAvailable(library)) {
      console.error(
        `Cannot refresh the snapshot: labs.json is not readable at ${library}.\n` +
          `Pass --library "<path to Claude Math Visual>".`
      );
      process.exitCode = 1;
      return;
    }
    const table = loadBenchStandards(library);
    writeSnapshot(table);
    console.log(`wrote ${table.size} benches to ${SNAPSHOT_PATH}`);
    return;
  }

  const report = runCcssDepthAudit(library);
  const { totals, rows } = report;
  const n = rows.length;

  if (args.includes("--json")) {
    console.log(JSON.stringify(report, null, 2));
    return;
  }

  if (csvIndex >= 0) {
    const path = args[csvIndex + 1];
    const esc = (v: unknown) => `"${String(v ?? "").replace(/"/g, '""')}"`;
    const header = [
      "standard", "grade", "domain", "domain_name", "cluster", "description",
      "tier", "instrument", "evidence", "reachability", "host_lab", "host_lab_title", "labs_claiming",
    ];
    const lines = [header.join(",")];
    for (const r of [...rows].sort(
      (a, b) => GRADE_ORDER.indexOf(a.grade) - GRADE_ORDER.indexOf(b.grade) || a.id.localeCompare(b.id)
    )) {
      lines.push([
        r.id, r.grade, r.domain, r.domainName, r.cluster, r.description,
        r.tier, r.instrument, r.evidence, r.reachability, r.hostLabId, r.hostLabTitle, r.labsClaiming,
      ].map(esc).join(","));
    }
    writeFileSync(path, lines.join("\n"));
    console.log(`wrote ${rows.length} rows to ${path}`);
    return;
  }

  const LABEL: Record<DepthTier, string> = {
    A: "A  Dedicated bench",
    B: "B  Shared bench",
    C: "C  Curated template",
    D: "D  Incidental (whole-domain)",
    E: "E  Taught but untracked",
    F: "F  Absent",
  };
  const pct = (x: number) => `${((x / n) * 100).toFixed(1)}%`;

  console.log("CCSS depth audit — what a student can actually reach\n");
  console.log(`  library                ${library}`);
  console.log(`  canonical standards    ${n}`);
  console.log(`  California labs        ${report.labsTotal} (${report.labsWholeDomain} claim a whole domain by auto-fill)`);
  console.log(`  benches                ${report.benchesPorted} (${report.benchesReachable} reachable, ${report.benchesOrphaned} orphaned)\n`);

  for (const tier of ["A", "B", "C", "D", "E", "F"] as DepthTier[]) {
    console.log(`  ${LABEL[tier].padEnd(30)} ${String(totals[tier]).padStart(4)}  ${pct(totals[tier]).padStart(6)}`);
  }
  const real = totals.A + totals.B + totals.E;
  const paper = totals.D + totals.F;
  console.log(`\n  real visual (A+B+E)            ${String(real).padStart(4)}  ${pct(real).padStart(6)}`);
  console.log(`  paper only  (D+F)              ${String(paper).padStart(4)}  ${pct(paper).padStart(6)}\n`);

  console.log("| grade | n | A | B | C | D | E | F | real visual | paper only |");
  console.log("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |");
  for (const g of report.byGrade) {
    const t = g.tiers;
    console.log(
      `| ${g.grade} | ${g.n} | ${t.A} | ${t.B} | ${t.C} | ${t.D} | ${t.E} | ${t.F} | ` +
        `${((g.realVisual / g.n) * 100).toFixed(0)}% | ${((g.paperOnly / g.n) * 100).toFixed(0)}% |`
    );
  }

  const absent = rows.filter((r) => r.tier === "F");
  if (absent.length > 0) {
    console.log(`\nStandards with no bench at all (${absent.length}):`);
    for (const r of absent.sort((a, b) => a.id.localeCompare(b.id))) {
      console.log(`  ${r.id.padEnd(11)} ${r.description}`);
    }
  }
}

/* run only when invoked directly, so the test can import the scorer */
if (process.argv[1] && process.argv[1].includes("audit-ccss-depth")) main();
