import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";

const repoRoot = path.resolve(new URL("..", import.meta.url).pathname);
const sourcePath = path.join(repoRoot, "scripts", "deploy-vercel-production.mjs");

test("production deploy gates promotion and final domain on dashboard latency smoke", async () => {
  const source = await readFile(sourcePath, "utf8");
  const inspectIndex = source.indexOf("vercel\", [\"inspect\", deploymentUrl");
  const preflightIndex = source.indexOf("await runPreflight();");
  const authPrecheckIndex = source.indexOf("assertDashboardSmokeAuthReady(", preflightIndex);
  const localBuildGateIndex = source.indexOf("const localBuildGate = await runReleaseBuildGate", authPrecheckIndex);
  const stagingIndex = source.indexOf("const staging = await prepareVercelStaging", localBuildGateIndex);
  const aiTutorGateIndex = source.indexOf("const aiTutorLatencyGate = await runAITutorLatencyGate(deploymentUrl);");
  const dashboardGateIndex = source.indexOf("const dashboardLatencyGate = await runDashboardLatencyGate(deploymentUrl,");
  const dashboardUiGateIndex = source.indexOf("const dashboardUiLoadingGate = await runDashboardUiLoadingGate(deploymentUrl,");
  const promoteIndex = source.indexOf("vercel\", [\"promote\", deploymentUrl");
  const productionDashboardGateIndex = source.indexOf("const productionDashboardLatencyGate = await runDashboardLatencyGate(productionBaseUrl,");
  const productionDashboardUiGateIndex = source.indexOf("const productionDashboardUiLoadingGate = await runDashboardUiLoadingGate(productionBaseUrl,");
  const dashboardFunctionIndex = source.indexOf("async function runDashboardLatencyGate(baseUrl,");
  const dashboardFunctionEnd = source.indexOf("async function runDashboardUiLoadingGate(baseUrl,", dashboardFunctionIndex);
  const dashboardUiFunctionIndex = source.indexOf("async function runDashboardUiLoadingGate(baseUrl,");
  const dashboardUiFunctionEnd = source.indexOf("function extractDeploymentUrl", dashboardUiFunctionIndex);
  const dashboardSmokeIndex = source.indexOf("\"scripts/dashboard-latency-smoke.mjs\"", dashboardFunctionIndex);
  const dashboardUiSmokeIndex = source.indexOf("\"scripts/dashboard-ui-loading-smoke.mjs\"", dashboardUiFunctionIndex);
  const recordIndex = source.indexOf("dashboardLatencyGate,", dashboardGateIndex);
  const uiRecordIndex = source.indexOf("dashboardUiLoadingGate,", dashboardUiGateIndex);
  const productionRecordIndex = source.indexOf("productionDashboardLatencyGate,", productionDashboardGateIndex);
  const productionUiRecordIndex = source.indexOf("productionDashboardUiLoadingGate,", productionDashboardUiGateIndex);
  const defaultProductionBaseUrlIndex = source.indexOf("const DEFAULT_PRODUCTION_SMOKE_BASE_URL = \"https://mais.ac\";");
  const dryRunProductionBaseUrlIndex = source.indexOf("productionBaseUrl,", source.indexOf("if (options.dryRun)"));
  const dryRunReturnIndex = source.indexOf("return {", source.indexOf("if (options.dryRun)"));
  const deployIndex = source.indexOf("const deployArgs = [", authPrecheckIndex);
  const authImportIndex = source.indexOf("import { assertDashboardSmokeAuthReady } from \"./dashboard-smoke-auth-precheck.mjs\";");
  const buildGateImportIndex = source.indexOf("import { runReleaseBuildGate } from \"./release-build-gate.mjs\";");

  assert.notEqual(preflightIndex, -1, "Production deploy should run staged publish preflight.");
  assert.notEqual(localBuildGateIndex, -1, "Production deploy should run a local isolated release build gate.");
  assert.notEqual(stagingIndex, -1, "Production deploy should prepare pruned staging after the build gate.");
  assert.notEqual(inspectIndex, -1, "Production deploy should inspect deployment before smoke gates.");
  assert.notEqual(aiTutorGateIndex, -1, "Production deploy should keep the AI Tutor latency gate.");
  assert.notEqual(dashboardGateIndex, -1, "Production deploy should run the pre-promotion dashboard latency gate.");
  assert.notEqual(dashboardUiGateIndex, -1, "Production deploy should run the pre-promotion dashboard UI loading gate.");
  assert.notEqual(promoteIndex, -1, "Production deploy should promote only after gates pass.");
  assert.notEqual(productionDashboardGateIndex, -1, "Production deploy should run a post-promotion production-domain dashboard latency gate.");
  assert.notEqual(productionDashboardUiGateIndex, -1, "Production deploy should run a post-promotion production-domain dashboard UI loading gate.");
  assert.notEqual(dashboardFunctionEnd, -1, "Dashboard gate function should be bounded.");
  assert.notEqual(dashboardUiFunctionIndex, -1, "Production deploy should define a dashboard UI loading gate.");
  assert.notEqual(dashboardUiFunctionEnd, -1, "Dashboard UI loading gate function should be bounded.");
  assert.notEqual(defaultProductionBaseUrlIndex, -1, "Production-domain smoke should have a default base URL.");
  assert.notEqual(dryRunProductionBaseUrlIndex, -1, "Dry-run output should report the production-domain smoke target.");
  assert.notEqual(authPrecheckIndex, -1, "Production deploy should require dashboard smoke auth before real deploy.");
  assert.notEqual(deployIndex, -1, "Production deploy should build deploy args after auth precheck.");
  assert.notEqual(authImportIndex, -1, "Production deploy should import the shared dashboard smoke auth precheck.");
  assert.notEqual(buildGateImportIndex, -1, "Production deploy should import the release build gate.");
  assert.ok(preflightIndex < authPrecheckIndex, "Staged publish preflight should run before dashboard smoke auth precheck.");
  assert.ok(authPrecheckIndex < localBuildGateIndex, "Real deploy auth readiness should be checked before the expensive local build gate.");
  assert.ok(localBuildGateIndex < stagingIndex, "Local build gate should pass before staging.");
  assert.ok(stagingIndex < dryRunReturnIndex, "Dry-run record should be returned after staging is prepared.");
  assert.ok(inspectIndex < aiTutorGateIndex, "Deployment inspect should complete before latency gates.");
  assert.ok(aiTutorGateIndex < dashboardGateIndex, "Pre-promotion dashboard gate should run after AI Tutor gate.");
  assert.ok(dashboardGateIndex < dashboardUiGateIndex, "Pre-promotion dashboard UI loading gate should run after dashboard API latency gate.");
  assert.ok(dashboardUiGateIndex < promoteIndex, "Pre-promotion dashboard UI loading gate must run before production promotion.");
  assert.ok(promoteIndex < productionDashboardGateIndex, "Production-domain dashboard smoke should run after promotion.");
  assert.ok(productionDashboardGateIndex < productionDashboardUiGateIndex, "Production-domain UI loading smoke should run after production-domain API smoke.");
  assert.match(source.slice(preflightIndex, localBuildGateIndex), /if \(!options\.dryRun\)/, "Dry-run should skip dashboard smoke auth precheck.");
  assert.ok(authPrecheckIndex < deployIndex, "Dashboard smoke auth precheck should run before creating a production deployment.");
  assert.ok(dashboardSmokeIndex > dashboardFunctionIndex, "Dashboard gate should invoke dashboard-latency-smoke.");
  assert.ok(dashboardUiSmokeIndex > dashboardUiFunctionIndex, "Dashboard UI gate should invoke dashboard-ui-loading-smoke.");
  assert.match(source.slice(dashboardFunctionIndex, dashboardFunctionEnd), /--base-url", baseUrl, "--json"/);
  assert.match(source.slice(dashboardUiFunctionIndex, dashboardUiFunctionEnd), /--base-url", baseUrl, "--json"/);
  assert.match(source.slice(dashboardGateIndex, promoteIndex), /production domains were not promoted/);
  assert.match(source.slice(dashboardUiGateIndex, promoteIndex), /Dashboard UI loading gate failed/);
  assert.match(source.slice(dashboardFunctionIndex, dashboardFunctionEnd), /current production domains remain on the previous production deployment/);
  assert.match(source.slice(dashboardFunctionIndex, dashboardFunctionEnd), /production-domain smoke did not pass/);
  assert.match(source.slice(dashboardUiFunctionIndex, dashboardUiFunctionEnd), /current production domains remain on the previous production deployment/);
  assert.match(source.slice(dashboardUiFunctionIndex, dashboardUiFunctionEnd), /production-domain UI loading smoke did not pass/);
  assert.match(source.slice(preflightIndex, localBuildGateIndex), /context: "Production deploy"/);
  assert.match(source.slice(dryRunReturnIndex, deployIndex), /localBuildGate/);
  assert.ok(recordIndex > dashboardGateIndex, "Deployment record should include dashboard latency evidence.");
  assert.ok(uiRecordIndex > dashboardUiGateIndex, "Deployment record should include dashboard UI loading evidence.");
  assert.ok(productionRecordIndex > productionDashboardGateIndex, "Deployment record should include production-domain dashboard latency evidence.");
  assert.ok(productionUiRecordIndex > productionDashboardUiGateIndex, "Deployment record should include production-domain dashboard UI loading evidence.");
});
