import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";

const repoRoot = path.resolve(new URL("..", import.meta.url).pathname);
const sourcePath = path.join(repoRoot, "scripts", "deploy-vercel-preview.mjs");

test("preview deploy verifies dashboard latency before release handoff", async () => {
  const source = await readFile(sourcePath, "utf8");
  const preflightIndex = source.indexOf("await runPreflight();");
  const authPrecheckIndex = source.indexOf("assertDashboardSmokeAuthReady(", preflightIndex);
  const localBuildGateIndex = source.indexOf("const localBuildGate = await runReleaseBuildGate", authPrecheckIndex);
  const stagingIndex = source.indexOf("const staging = await prepareVercelStaging", localBuildGateIndex);
  const dryRunIndex = source.indexOf("if (options.dryRun)", stagingIndex);
  const deployIndex = source.indexOf("const deployResult = await runCommand(\"vercel\"", stagingIndex);
  const inspectIndex = source.indexOf("vercel\", [\"inspect\", deploymentUrl");
  const dashboardGateIndex = source.indexOf("const dashboardLatencyGate = await runDashboardLatencyGate(deploymentUrl);");
  const dashboardUiGateIndex = source.indexOf("const dashboardUiLoadingGate = await runDashboardUiLoadingGate(deploymentUrl);");
  const recordIndex = source.indexOf("dashboardUiLoadingGate,", dashboardUiGateIndex);
  const dryRunParseIndex = source.indexOf("dryRun: false");
  const dryRunArgIndex = source.indexOf("arg === \"--dry-run\"");
  const authImportIndex = source.indexOf("import { assertDashboardSmokeAuthReady } from \"./dashboard-smoke-auth-precheck.mjs\";");
  const buildGateImportIndex = source.indexOf("import { runReleaseBuildGate } from \"./release-build-gate.mjs\";");
  const dashboardFunctionIndex = source.indexOf("async function runDashboardLatencyGate(deploymentUrl)");
  const dashboardUiFunctionIndex = source.indexOf("async function runDashboardUiLoadingGate(deploymentUrl)");
  const dashboardFunctionEnd = source.indexOf("async function runDashboardUiLoadingGate", dashboardFunctionIndex);
  const dashboardUiFunctionEnd = source.indexOf("function extractDeploymentUrl", dashboardUiFunctionIndex);

  assert.notEqual(preflightIndex, -1, "Preview deploy should run release preflight.");
  assert.notEqual(localBuildGateIndex, -1, "Preview deploy should run a local isolated release build gate.");
  assert.notEqual(stagingIndex, -1, "Preview deploy should prepare pruned staging.");
  assert.notEqual(dryRunIndex, -1, "Preview deploy should support a dry-run path.");
  assert.notEqual(authPrecheckIndex, -1, "Preview deploy should require dashboard smoke auth before deploy.");
  assert.notEqual(deployIndex, -1, "Preview deploy should create a Vercel deployment.");
  assert.notEqual(inspectIndex, -1, "Preview deploy should inspect the deployment.");
  assert.notEqual(dashboardGateIndex, -1, "Preview deploy should run dashboard latency smoke.");
  assert.notEqual(dashboardUiGateIndex, -1, "Preview deploy should run dashboard UI loading smoke.");
  assert.notEqual(authImportIndex, -1, "Preview deploy should import the shared dashboard smoke auth precheck.");
  assert.notEqual(buildGateImportIndex, -1, "Preview deploy should import the release build gate.");
  assert.notEqual(dashboardFunctionIndex, -1, "Preview deploy should define a dashboard latency gate.");
  assert.notEqual(dashboardUiFunctionIndex, -1, "Preview deploy should define a dashboard UI loading gate.");
  assert.notEqual(dashboardFunctionEnd, -1, "Dashboard gate function should be bounded.");
  assert.notEqual(dashboardUiFunctionEnd, -1, "Dashboard UI gate function should be bounded.");
  assert.notEqual(dryRunParseIndex, -1, "Preview deploy should define dryRun option default.");
  assert.notEqual(dryRunArgIndex, -1, "Preview deploy should parse --dry-run.");
  assert.ok(preflightIndex < authPrecheckIndex, "Preflight should run before dashboard smoke auth precheck.");
  assert.ok(authPrecheckIndex < localBuildGateIndex, "Real deploy auth readiness should be checked before the expensive local build gate.");
  assert.ok(localBuildGateIndex < stagingIndex, "Local build gate should pass before staging.");
  assert.ok(preflightIndex < stagingIndex, "Preflight should run before staging.");
  assert.ok(stagingIndex < dryRunIndex, "Dry-run should be checked after staging is planned.");
  assert.match(source.slice(preflightIndex, localBuildGateIndex), /if \(!options\.dryRun\)/, "Dry-run should skip dashboard smoke auth precheck.");
  assert.ok(authPrecheckIndex < deployIndex, "Dashboard smoke auth precheck should run before creating a deployment.");
  assert.ok(inspectIndex < dashboardGateIndex, "Preview should be inspected before dashboard latency smoke.");
  assert.ok(dashboardGateIndex < dashboardUiGateIndex, "Preview should run UI loading smoke after dashboard API latency smoke.");
  assert.ok(recordIndex > dashboardUiGateIndex, "Preview deployment record should include dashboard UI loading evidence.");
  assert.match(source.slice(stagingIndex, dryRunIndex), /dryRun: options\.dryRun/);
  assert.match(source.slice(dryRunIndex, deployIndex), /localBuildGate/);
  assert.match(source.slice(dryRunIndex, deployIndex), /deployed: false/);
  assert.match(source.slice(inspectIndex, dashboardGateIndex), /"--wait"/);
  assert.match(source.slice(inspectIndex, dashboardGateIndex), /"--timeout", "5m"/);
  assert.match(source.slice(preflightIndex, localBuildGateIndex), /context: "Preview deploy"/);
  assert.match(source.slice(dashboardFunctionIndex, dashboardFunctionEnd), /"scripts\/dashboard-latency-smoke\.mjs", "--base-url", deploymentUrl, "--json"/);
  assert.match(source.slice(dashboardFunctionIndex, dashboardFunctionEnd), /not release-ready for production promotion/);
  assert.match(source.slice(dashboardUiFunctionIndex, dashboardUiFunctionEnd), /"scripts\/dashboard-ui-loading-smoke\.mjs", "--base-url", deploymentUrl, "--json"/);
  assert.match(source.slice(dashboardUiFunctionIndex, dashboardUiFunctionEnd), /loading state did not clear/);
});
