import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {
  isLivePremiumThreeDLab,
  projectPremiumThreeDDirectLab
} from "../components/visualizations/three/premiumThreeDLiveContract";
import { visualizationLabCatalog, type FeaturedLabDefinition } from "../data/visualizationLabs";

function argumentValue(name: string) {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1]?.trim() : undefined;
}

const outputPath = path.resolve(
  argumentValue("--output") ??
    "components/visualizations/generated/premiumThreeDDirectCatalog.generated.ts"
);
const checkOnly = process.argv.includes("--check");

function compareLabIds(left: FeaturedLabDefinition, right: FeaturedLabDefinition) {
  if (left.labId < right.labId) return -1;
  if (left.labId > right.labId) return 1;
  return 0;
}

const selectedLabs = visualizationLabCatalog
  .filter(isLivePremiumThreeDLab)
  .sort(compareLabIds);

assert.equal(
  new Set(selectedLabs.map((lab) => lab.labId)).size,
  selectedLabs.length,
  "Premium direct snapshot lab IDs must be unique."
);
for (const lab of selectedLabs) {
  assert.equal(lab.threeD?.enabled, true, `${lab.labId} live snapshot entry must have threeD.enabled=true.`);
  assert.equal(lab.threeD?.premiumLaunch, true, `${lab.labId} live snapshot entry must have premiumLaunch=true.`);
}

const snapshot = Object.fromEntries(
  selectedLabs.map((lab) => [
    lab.labId,
    projectPremiumThreeDDirectLab(lab) satisfies FeaturedLabDefinition
  ])
);
const liveLabIds = selectedLabs.map((lab) => lab.labId);
assert.deepEqual(Object.keys(snapshot), liveLabIds, "Live premium snapshot keys must equal the sorted live lab IDs.");

const generatedSource = `/* eslint-disable */
// AUTO-GENERATED by scripts/generate-premium-three-d-direct-catalog-snapshot.mts.
// Runtime code imports this catalog-decoupled snapshot instead of the full catalog.
// Regenerate; do not hand-edit student-facing metadata here.
import type { FeaturedLabDefinition } from "@/data/visualizationLabs";

export const premiumThreeDDirectCatalogSnapshot: Readonly<Record<string, FeaturedLabDefinition>> = ${JSON.stringify(snapshot, null, 2)};

export const premiumThreeDDirectLabIds = ${JSON.stringify(liveLabIds, null, 2)} as const;
`;

if (checkOnly) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8") : "";
  assert.equal(current, generatedSource, `${path.relative(process.cwd(), outputPath)} is stale; regenerate the premium direct snapshot.`);
  console.log(`global premium direct snapshot current: ${selectedLabs.length} live labs -> ${path.relative(process.cwd(), outputPath)}`);
} else {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, generatedSource);
  console.log(`generated global premium direct snapshot: ${selectedLabs.length} live labs -> ${path.relative(process.cwd(), outputPath)}`);
}
